/**
 * @file Oracle.hpp
 * @brief Independent test oracle and fixtures for the dtype-casting suites.
 *
 * @li referenceDecode() / referenceEncode() re-derive reduced-format
 *     semantics from a declarative FormatSpec (exponent width, bias,
 *     special-value availability) using exact dyadic arithmetic in
 *     @c double. A wrong constant on either side fails a test instead of
 *     cancelling out.
 * @li The pair registry (allPairs()) is generated by re-expanding the X-macro
 *     families in @ref ncore/headeronly/cast.h, so codegen drift breaks the
 *     count assertion rather than silently passing.
 * @li Tensor fixtures follow the ownership conventions of
 *     @c ncore/tests/core/utils/TensorUtils.hpp (TensorCXX owns, raw views go
 *     to the C API), extended with packing-aware raw element access for
 *     Float4E2M1fn.
 *
 * All generators are deterministic: fixed seeds, no global state.
 */

#pragma once

#include <gtest/gtest.h>

#include <cmath>
#include <cstdint>
#include <cstring>
#include <limits>
#include <string>
#include <string_view>
#include <type_traits>
#include <vector>

#include <ncore/core/device.h>
#include <ncore/core/dtype.h>
#include <ncore/headeronly/cast.h>
#include <ncore/headeronly/macros.h>
#include <ncore/headeronly/wrappers/tensor.hh>
#include <ncore/native/cpu/dtype/casting.h>
#include <ncore/simd/simd.h>
#include <ncore/tables/cast_tables.h>
#include <ncore/tensor.h>

namespace tests::casting {

/// Default seed for deterministic fills ("NOVA" in ASCII), matching the core
/// test utilities.
constexpr uint32_t kDefaultSeed = 0x4E4F5641u;

/* ==========================================================================
 * Format model: declared independently of the public headers
 * ========================================================================== */

/**
 * @struct FormatSpec
 * @brief Declarative description of one reduced-precision format.
 */
struct FormatSpec {
  int expBits; ///< Width of the biased exponent field.
  int manBits; ///< Width of the explicit mantissa field.
  int bias;    ///< Exponent bias.
  bool hasInf; ///< Whether an infinity encoding exists.
  bool hasNan; ///< Whether a NaN encoding exists.
};

inline constexpr FormatSpec kFp16{
    .expBits = 5, .manBits = 10, .bias = 15, .hasInf = true, .hasNan = true};
inline constexpr FormatSpec kBf16{
    .expBits = 8, .manBits = 7, .bias = 127, .hasInf = true, .hasNan = true};
inline constexpr FormatSpec kFp8E4M3{
    .expBits = 4, .manBits = 3, .bias = 7, .hasInf = false, .hasNan = true};
inline constexpr FormatSpec kFp8E5M2{
    .expBits = 5, .manBits = 2, .bias = 15, .hasInf = true, .hasNan = true};
inline constexpr FormatSpec kFp4E2M1{
    .expBits = 2, .manBits = 1, .bias = 1, .hasInf = false, .hasNan = false};
// Full-IEEE widths share the same declarative model; specOf() hands them
// out too so the field math below covers every floating dtype.
inline constexpr FormatSpec kF32{
    .expBits = 8, .manBits = 23, .bias = 127, .hasInf = true, .hasNan = true};
inline constexpr FormatSpec kF64{
    .expBits = 11, .manBits = 52, .bias = 1023, .hasInf = true, .hasNan = true};

/**
 * @brief Total storage width of a format in bits, sign bit included.
 *
 * @param[in] f Format description.
 * @return Total width in bits.
 */
constexpr int totalBits(FormatSpec f) { return 1 + f.expBits + f.manBits; }

/**
 * @brief Largest finite raw magnitude of a format (sign bit excluded).
 *
 * Reserved exponent fields reduce the finite domain:
 * @li Formats with infinity lose their whole top exponent binade.
 * @li Formats without infinity but with NaN (E4M3FN) keep the top binade
 *     except its all-ones mantissa slot, which encodes NaN.
 * @li Finite-only formats keep every pattern.
 *
 * @param[in] f Format description.
 * @return Raw magnitude pattern of the largest finite value.
 */
constexpr uint64_t maxFiniteMagnitude(FormatSpec f) {
  const uint64_t maxExpField = (1ULL << f.expBits) - 1ULL;
  const uint64_t manMask = (1ULL << f.manBits) - 1ULL;
  if (f.hasInf) {
    return ((maxExpField - 1ULL) << f.manBits) | manMask;
  }
  if (f.hasNan) {
    return (maxExpField << f.manBits) | (manMask - 1ULL);
  }
  return (maxExpField << f.manBits) | manMask;
}

/**
 * @brief Smallest positive normal raw magnitude (sign bit excluded).
 *
 * @param[in] f Format description.
 * @return Raw magnitude pattern of the smallest normal value.
 */
constexpr uint64_t minNormalMagnitude(FormatSpec f) {
  return 1ULL << f.manBits;
}

/**
 * @brief Smallest positive subnormal raw magnitude (sign bit excluded).
 *
 * @param[in] f Format description.
 * @return Raw magnitude pattern of the smallest subnormal value.
 */
constexpr uint64_t minSubnormalMagnitude(FormatSpec f) {
  (void)f;
  return 1ULL;
}

/* ==========================================================================
 * Reference decode: exact dyadic arithmetic
 * ========================================================================== */

/**
 * @brief Exact value of a raw storage pattern as a @c double.
 *
 * Every reduced-format value is a dyadic rational, so the result is exact.
 * The sign is applied last; infinities map to +/-inf via HUGE_VAL.
 *
 * @param[in] f       Format description.
 * @param[in] pattern Raw storage pattern (zero-extended to 64 bits).
 * @return Exact numeric value; NaN patterns yield a quiet NaN.
 */
inline double referenceDecode(FormatSpec f, uint64_t pattern) {
  const auto manBits = static_cast<uint32_t>(f.manBits);
  const auto total = static_cast<uint32_t>(totalBits(f));
  const bool neg = ((pattern >> (total - 1)) & 1U) != 0U;
  const uint32_t maxExpField = (1U << f.expBits) - 1U;
  const uint32_t expField =
      static_cast<uint32_t>((pattern >> manBits) & maxExpField);
  const uint32_t man = static_cast<uint32_t>(pattern & ((1ULL << manBits) - 1));

  double out = 0.0;
  if (expField == 0) {
    // Zero or subnormal: man * 2^(1 - bias - manBits).
    out = std::ldexp(static_cast<double>(man), 1 - f.bias - f.manBits);
  } else if (expField == maxExpField && f.hasInf) {
    // Reserved exponent field with infinity: mantissa zero is infinity,
    // anything else is NaN.
    out = (man == 0) ? HUGE_VAL : std::numeric_limits<double>::quiet_NaN();
  } else if (expField == maxExpField && f.hasNan &&
             man == static_cast<uint32_t>((1ULL << manBits) - 1)) {
    // Finite-only formats (E4M3FN): exactly one NaN slot at the top of
    // the top binade; every other top-binade pattern is a normal number
    // (e.g. 0x7E decodes to 448, the format's largest finite value).
    out = std::numeric_limits<double>::quiet_NaN();
  } else {
    // Normal: (1 + man / 2^manBits) * 2^(expField - bias).
    const double scale = std::ldexp(1.0, expField - f.bias);
    out = (1.0 + (static_cast<double>(man) / std::ldexp(1.0, manBits))) * scale;
  }
  return neg ? -out : out;
}

/* ==========================================================================
 * Reference encode: round-to-nearest-even plus documented overflow policy
 *
 * Finite inputs are handled purely mathematically. Non-finite inputs follow
 * the per-format saturation policy (infinity stays infinity when the format
 * has one, otherwise saturates to max finite; NaN maps to the canonical
 * all-ones NaN). NaN payload handling differs across conversion paths and is
 * therefore asserted by SpecialValueInvariant through policy tables, never
 * through this encoder.
 * ========================================================================== */

namespace detail {

/**
 * @brief Round-to-nearest-even for a non-negative dyadic rational.
 *
 * @param[in] x Value to round; must be non-negative and small enough that
 *              floor() is exact.
 * @return Nearest integer-valued double, ties resolved to even.
 */
inline double roundHalfToEven(double x) {
  const double fl = std::floor(x);
  const double diff = x - fl;
  if (diff > 0.5) {
    return fl + 1.0;
  }
  if (diff < 0.5) {
    return fl;
  }
  // Exact tie: round to the even integer.
  return std::fmod(fl, 2.0) != 0.0 ? fl + 1.0 : fl;
}

} // namespace detail

/**
 * @brief Round-to-nearest-even quantization of a double into format @p f.
 *
 * @param[in] f Format description.
 * @param[in] v Value to encode.
 * @return Raw storage pattern (sign included).
 */
inline uint64_t referenceEncode(FormatSpec f, double v) {
  const auto manBits = static_cast<uint32_t>(f.manBits);
  const auto total = static_cast<uint32_t>(totalBits(f));
  // Exact for -0.0: Release builds carry -fsigned-zeros, so the sign of a
  // zero is never optimized away.
  const uint64_t sign = std::signbit(v) ? (1ULL << (total - 1)) : 0ULL;
  const uint64_t maxExpField = (1ULL << f.expBits) - 1ULL;
  const uint64_t manMask = (1ULL << manBits) - 1ULL;
  const int emin = 1 - f.bias;
  // Formats without infinity keep their whole top exponent binade finite,
  // so the normal maximum extends past the IEEE bias (E4M3FN: 8, FP4: 2).
  const int emax =
      f.hasInf ? f.bias : static_cast<int>((1ULL << f.expBits) - 1ULL) - f.bias;

  if (std::isnan(v)) {
    return sign | (maxExpField << manBits) | manMask;
  }
  if (std::isinf(v)) {
    return f.hasInf ? (sign | (maxExpField << manBits))
                    : (sign | maxFiniteMagnitude(f));
  }

  const double a = std::fabs(v);
  if (a == 0.0) {
    return sign;
  }

  int ea = 0;
  std::frexp(a, &ea);   // a = frac * 2^ea with frac in [0.5, 1)
  const int e = ea - 1; // Unbiased binary exponent.

  uint64_t expField = 0;
  uint64_t man = 0;
  if (e >= emin) {
    // Normal range (or rounding up from the smallest normal binade).
    const double q = std::ldexp(a, f.manBits - e); // in [2^m, 2^(m+1))
    double qr = detail::roundHalfToEven(q);
    int e2 = e;
    if (qr >= std::ldexp(1.0, f.manBits + 1)) { // Mantissa carry.
      qr = std::ldexp(1.0, f.manBits);
      e2 += 1;
    }
    if (e2 > emax) {
      // Overflow: infinity when available, else saturate to max finite.
      return f.hasInf ? (sign | (maxExpField << manBits))
                      : (sign | maxFiniteMagnitude(f));
    }
    expField = static_cast<uint64_t>(e2 + f.bias);
    man = static_cast<uint64_t>(qr) - (1ULL << manBits);
  } else {
    // Subnormal territory (possibly rounding up to the smallest normal).
    const double q = std::ldexp(a, f.manBits - emin); // Units of the step.
    const double qr = detail::roundHalfToEven(q);
    if (qr == 0.0) {
      return sign; // Flush to zero.
    }
    if (qr >= std::ldexp(1.0, f.manBits)) {
      expField = 1; // Smallest normal.
      man = 0;
    } else {
      expField = 0;
      man = static_cast<uint64_t>(qr);
    }
  }
  return sign | (expField << manBits) | man;
}

/* ==========================================================================
 * Reference integer-conversion policies
 * ========================================================================== */

/**
 * @brief Reference float-to-int conversion mirroring the cast kernels:
 *        NaN maps to 0, out-of-range values clamp in the SOURCE float
 *        precision, then the value truncates toward zero.
 *
 * The kernels clamp at the largest value of the source float type strictly
 * below the exclusive destination bound and convert that constant: an
 * f32-sourced kernel yields 2147483520 for s32 overflow while an f64-
 * sourced one yields INT32_MAX. The oracle derives the same constants via
 * @c std::nextafter instead of hardcoding them.
 *
 * @tparam D Destination integer type.
 * @param[in] v   Source value (already quantized to the source format).
 * @param[in] src Source floating dtype (reduced formats narrow through
 *                float first, so they follow the Float32 rule).
 * @return Saturated, truncated conversion of @p v.
 */
template <typename D> D referenceSaturate(double v, DType_ src) {
  static_assert(std::is_integral_v<D>);
  if (std::isnan(v)) {
    return D{0};
  }
  const double lo = static_cast<double>(std::numeric_limits<D>::min());
  if (v <= lo) {
    return std::numeric_limits<D>::min();
  }
  // Exclusive upper bound: a power of two, exact in both float widths.
  const double hiBound =
      static_cast<double>(std::numeric_limits<D>::max()) + 1.0;
  if (v >= hiBound) {
    const double hi = (src == DType_::Float64)
                          ? std::nextafter(hiBound, 0.0)
                          : static_cast<double>(std::nextafter(
                                static_cast<float>(hiBound), 0.0F));
    return static_cast<D>(hi);
  }
  return static_cast<D>(v);
}

/**
 * @brief True when an int->int kernel clamps into the destination range
 *        instead of truncating modularly: every narrowing whose target is
 *        8-bit wide, plus u8 -> s8. All other width/sign changes are plain
 *        C conversions (modular two's-complement truncation), verified
 *        against the scalar kernels in @c DTypeCasting.c.
 *
 * @tparam S Source integer type.
 * @tparam D Destination integer type.
 */
template <typename S, typename D>
constexpr bool kKernelClamps =
    (sizeof(D) == sizeof(char) && sizeof(S) > sizeof(D)) ||
    (std::is_same_v<S, uint8_t> && std::is_same_v<D, int8_t>);

/**
 * @brief Reference integer conversion mirroring the kernels' per-pair
 *        policy: clamping kernels clamp @p v into D's range and convert;
 *        every other pair converts modularly like a plain C cast.
 *
 * @tparam S Source integer type.
 * @tparam D Destination integer type.
 * @param[in] v Source value.
 * @return Converted value per the kernel policy for (S, D).
 */
template <typename S, typename D> D referenceNarrow(S v) {
  static_assert(std::is_integral_v<S> && std::is_integral_v<D>);
  if constexpr (kKernelClamps<S, D>) {
    if constexpr (std::is_signed_v<S>) {
      // Signed source: clamp into [D::min, D::max] on both sides.
      const int64_t x = static_cast<int64_t>(v);
      constexpr int64_t lo =
          static_cast<int64_t>(std::numeric_limits<D>::min());
      constexpr int64_t hi =
          static_cast<int64_t>(std::numeric_limits<D>::max());
      if (x <= lo) {
        return std::numeric_limits<D>::min();
      }
      if (x >= hi) {
        return std::numeric_limits<D>::max();
      }
      return static_cast<D>(x);
    } else {
      // Unsigned source: nothing below the destination range exists, so
      // only the high side clamps: this matches the kernels' high-only
      // ternaries (e.g. tu16_to_s8, tu32_to_u8).
      const uint64_t x = static_cast<uint64_t>(v);
      constexpr uint64_t hi =
          static_cast<uint64_t>(std::numeric_limits<D>::max());
      if (x >= hi) {
        return std::numeric_limits<D>::max();
      }
      return static_cast<D>(x);
    }
  } else {
    // Modular path: truncate to D's width and reinterpret. C++20 and
    // later define both steps (two's-complement), matching the plain-cast
    // kernels on every supported compiler.
    using U = std::make_unsigned_t<D>;
    const uint64_t wide = std::is_signed_v<S>
                              ? static_cast<uint64_t>(static_cast<int64_t>(v))
                              : static_cast<uint64_t>(v);
    return static_cast<D>(static_cast<U>(wide));
  }
}

/* ==========================================================================
 * Pair registry: generated from the cast.h X-macro families
 * ========================================================================== */

/**
 * @brief Maps a cast.h short dtype name to its DType_ value.
 *
 * @param[in] name Short name as used by the X-macro families ("fp16", "s8",
 *                 ...).
 * @return Matching DType_ enumerator; Float32 for unrecognized names (the
 *         registry never passes anything else).
 */
inline DType_ dtypeFrom(std::string_view name) {
  if (name == "fp16") {
    return DType_::Float16;
  }
  if (name == "f32") {
    return DType_::Float32;
  }
  if (name == "f64") {
    return DType_::Float64;
  }
  if (name == "bf16") {
    return DType_::BFloat16;
  }
  if (name == "fp8e4m3") {
    return DType_::Float8E4M3fn;
  }
  if (name == "fp8e5m2") {
    return DType_::Float8E5M2;
  }
  if (name == "fp4e2m1") {
    return DType_::Float4E2M1fn;
  }
  if (name == "s8") {
    return DType_::Signed8;
  }
  if (name == "s16") {
    return DType_::Signed16;
  }
  if (name == "s32") {
    return DType_::Signed32;
  }
  if (name == "s64") {
    return DType_::Signed64;
  }
  if (name == "u8") {
    return DType_::UnSigned8;
  }
  if (name == "u16") {
    return DType_::UnSigned16;
  }
  if (name == "u32") {
    return DType_::UnSigned32;
  }
  if (name == "u64") {
    return DType_::UnSigned64;
  }
  return DType_::Float32;
}

/**
 * @brief True when @p d is one of the seven floating dtypes.
 *
 * @param[in] d Dtype to classify.
 * @return True for Float32/Float64/Float16/BFloat16/FP8/FP4.
 */
constexpr bool isFloatDtype(DType_ d) {
  switch (d) {
  case DType_::Float32:
  case DType_::Float64:
  case DType_::Float16:
  case DType_::BFloat16:
  case DType_::Float8E4M3fn:
  case DType_::Float8E5M2:
  case DType_::Float4E2M1fn:
    return true;
  default:
    return false;
  }
}

/**
 * @brief Declarative format description for any floating dtype.
 *
 * @param[in] d Floating dtype.
 * @return Matching FormatSpec; the full-IEEE widths use their real field
 *         layout so the shared decode/encode/field math applies to them
 *         too.
 */
inline FormatSpec specOf(DType_ d) {
  switch (d) {
  case DType_::Float16:
    return kFp16;
  case DType_::BFloat16:
    return kBf16;
  case DType_::Float8E4M3fn:
    return kFp8E4M3;
  case DType_::Float8E5M2:
    return kFp8E5M2;
  case DType_::Float4E2M1fn:
    return kFp4E2M1;
  case DType_::Float32:
    return kF32;
  case DType_::Float64:
    return kF64;
  default:
    return kFp16;
  }
}

/**
 * @struct PairInfo
 * @brief One supported (src, dst) cast pair with its callable entry points.
 */
struct PairInfo {
  DType_ src;        ///< Source dtype.
  DType_ dst;        ///< Destination dtype.
  CastFn wrapper;    ///< tSRC_to_DST dispatch wrapper from cast.h.
  CastFn scalar;     ///< tSRC_to_DST_scalar portable kernel.
  std::string label; ///< Human-readable "src->dst" tag.
};

/**
 * @brief Builds the full registry of supported cast pairs by expanding the
 *        seven X-macro families once.
 *
 * @return Registry holding exactly 210 entries (asserted by callers).
 */
inline std::vector<PairInfo> buildAllPairs() {
  std::vector<PairInfo> pairs;
  pairs.reserve(210);
#define NOVA_TEST_PUSH_PAIR(FROM, TO)                                          \
  pairs.push_back(PairInfo{.src = dtypeFrom(#FROM),                            \
                           .dst = dtypeFrom(#TO),                              \
                           .wrapper = &t##FROM##_to_##TO,                      \
                           .scalar = &t##FROM##_to_##TO##_scalar,              \
                           .label = #FROM "->" #TO});
  CAST_FP_TYPES(NOVA_TEST_PUSH_PAIR)
  CAST_FP_TO_INT(NOVA_TEST_PUSH_PAIR)
  CAST_INT_TO_FP(NOVA_TEST_PUSH_PAIR)
  CAST_SINT_TO_SINT(NOVA_TEST_PUSH_PAIR)
  CAST_UINT_TO_UINT(NOVA_TEST_PUSH_PAIR)
  CAST_SINT_TO_UINT(NOVA_TEST_PUSH_PAIR)
  CAST_UINT_TO_SINT(NOVA_TEST_PUSH_PAIR)
#undef NOVA_TEST_PUSH_PAIR
  return pairs;
}

/**
 * @brief Process-wide pair registry (thread-safe magic static).
 *
 * @return Immutable reference to the 210-entry pair list.
 */
inline const std::vector<PairInfo> &allPairs() {
  static const std::vector<PairInfo> pairs = buildAllPairs();
  return pairs;
}

/* ==========================================================================
 * Bit reinterpretation helpers (memcpy-based, strict-aliasing safe)
 * ========================================================================== */

/**
 * @brief Reinterprets a float as its 32-bit pattern.
 *
 * @param[in] v Input value.
 * @return Raw IEEE 754 binary32 bits.
 */
inline uint32_t f32BitsOf(float v) {
  uint32_t w = 0;
  std::memcpy(&w, &v, sizeof(w));
  return w;
}

/**
 * @brief True when raw binary32 bits encode a NaN.
 *
 * Bit-level on purpose: the input is a storage pattern, not a float
 * object, so classification must not round-trip through the FP type.
 *
 * @param[in] w Raw IEEE 754 binary32 bits.
 * @return NaN classification.
 */
inline bool isNaNF32Bits(uint32_t w) {
  return (w & 0x7F800000U) == 0x7F800000U && (w & 0x007FFFFFU) != 0U;
}

/**
 * @brief True when raw binary32 bits encode infinity.
 *
 * @param[in] w Raw IEEE 754 binary32 bits.
 * @return Infinity classification.
 */
inline bool isInfF32Bits(uint32_t w) {
  return (w & 0x7FFFFFFFU) == 0x7F800000U;
}

/**
 * @brief Extracts the sign bit from raw binary32 bits.
 *
 * @param[in] w Raw IEEE 754 binary32 bits.
 * @return True when negative (sign bit set).
 */
inline bool signBitF32Bits(uint32_t w) { return (w >> 31) != 0U; }

/**
 * @brief Reinterprets a double as its 64-bit pattern.
 *
 * @param[in] v Input value.
 * @return Raw IEEE 754 binary64 bits.
 */
inline uint64_t f64BitsOf(double v) {
  uint64_t w = 0;
  std::memcpy(&w, &v, sizeof(w));
  return w;
}

/**
 * @brief True when a raw pattern of @p dtype encodes NaN (field-level
 *        decision on the storage bits).
 *
 * Supports all seven floating dtypes: full-IEEE widths use their wider
 * exponent/mantissa fields; reduced formats follow their documented NaN
 * slot rules (E4M3FN: single all-ones slot; FP4: none).
 *
 * @param[in] dtype   Floating dtype.
 * @param[in] pattern Raw storage pattern (zero-extended).
 * @return NaN classification.
 */
inline bool isNaNPattern(DType_ dtype, uint64_t pattern) {
  if (dtype == DType_::Float32) {
    const uint32_t w = static_cast<uint32_t>(pattern);
    return (w & 0x7F800000U) == 0x7F800000U && (w & 0x007FFFFFU) != 0U;
  }
  if (dtype == DType_::Float64) {
    return ((pattern >> 52) & 0x7FFULL) == 0x7FFULL &&
           (pattern & ((1ULL << 52) - 1ULL)) != 0ULL;
  }
  const FormatSpec spec = specOf(dtype);
  if (!spec.hasNan) {
    return false;
  }
  const uint64_t maxExpField = (1ULL << spec.expBits) - 1ULL;
  const uint64_t expField = (pattern >> spec.manBits) & maxExpField;
  const uint64_t man = pattern & ((1ULL << spec.manBits) - 1ULL);
  if (expField != maxExpField) {
    return false;
  }
  return spec.hasInf ? (man != 0ULL) : (man == ((1ULL << spec.manBits) - 1ULL));
}

/**
 * @brief The exact value a source tensor holds after writing @p v into it:
 *        full-IEEE sources narrow natively, reduced sources quantize
 *        through the reference encoder.
 *
 * @param[in] src Source floating dtype.
 * @param[in] v   Value about to be stored.
 * @return Value actually stored (exact in double).
 */
inline double quantizeToSource(DType_ src, double v) {
  switch (src) {
  case DType_::Float32:
    return static_cast<double>(static_cast<float>(v));
  case DType_::Float64:
    return v;
  default:
    return referenceDecode(specOf(src), referenceEncode(specOf(src), v));
  }
}

/* ==========================================================================
 * Deterministic fill (same LCG as the core test utilities)
 * ========================================================================== */

/**
 * @brief Fills a buffer with the core suites' LCG byte pattern.
 *
 * Same inputs produce the same bytes on every platform; no global state.
 *
 * @param[out] buf   Destination buffer.
 * @param[in]  bytes Size in bytes.
 * @param[in]  seed  LCG seed.
 */
inline void fillPattern(void *buf, size_t bytes, uint32_t seed) {
  auto *out = static_cast<uint8_t *>(buf);
  uint32_t state = seed;
  for (size_t i = 0; i < bytes; ++i) {
    state = (state * 1664525U) + 1013904223U;
    out[i] = static_cast<uint8_t>(state >> 24);
  }
}

/* ==========================================================================
 * Tensor fixtures -- packing-aware raw access
 * ========================================================================== */

/**
 * @struct CastPair
 * @brief An owned src/dst CPU tensor pair for one cast kernel invocation.
 */
struct CastPair {
  ncore::wrappers::TensorCXX src; ///< Owned source tensor.
  ncore::wrappers::TensorCXX dst; ///< Owned destination tensor.
  bool ok = false;                ///< True when both allocations succeeded.
};

/**
 * @brief Allocates a 1-D CPU src/dst pair holding @p logicalCount logical
 *        elements each.
 *
 * The count rounds up to an even value when either side is Float4E2M1fn
 * (packed dtypes require an even logical length). Both buffers are filled
 * with the deterministic LCG pattern so uninitialized reads are visible.
 *
 * @param[in] from         Source dtype.
 * @param[in] to           Destination dtype.
 * @param[in] logicalCount Logical element count.
 * @param[in] seed         LCG seed for both fills.
 * @return Pair descriptor; check @ref CastPair::ok before use.
 */
[[nodiscard]] inline CastPair makePair(DType_ from, DType_ to,
                                       size_t logicalCount, uint32_t seed) {
  CastPair pair;
  size_t n = logicalCount;
  if (dtype_packing_factor(from) == 2 || dtype_packing_factor(to) == 2) {
    n += n % 2;
  }
  novaStatus_t st{};
  constexpr bool kNoGrad = false;
  constexpr bool kNoPin = false;
  pair.src = ncore::wrappers::TensorCXX(std::vector<size_t>{n}, from,
                                        DEVICE_CPU, kNoGrad, kNoPin, &st);
  if (st.err != novaSuccess) {
    ADD_FAILURE() << "makePair: src allocation failed: "
                  << (st.message != nullptr ? st.message : "");
    return pair;
  }
  pair.dst = ncore::wrappers::TensorCXX(std::vector<size_t>{n}, to, DEVICE_CPU,
                                        kNoGrad, kNoPin, &st);
  if (st.err != novaSuccess) {
    ADD_FAILURE() << "makePair: dst allocation failed: "
                  << (st.message != nullptr ? st.message : "");
    return pair;
  }
  pair.ok = true;
  fillPattern(pair.src.mutableCTensor().data.data,
              pair.src.getSize() * pair.src.itemSize(), seed);
  fillPattern(pair.dst.mutableCTensor().data.data,
              pair.dst.getSize() * pair.dst.itemSize(), seed ^ 0xFFFFFFFFU);
  return pair;
}

/**
 * @brief Writes the low bytes of @p pattern into logical element @p idx.
 *
 * Packing-aware: for Float4E2M1fn, @p idx selects one nibble (low nibble
 * first) inside the addressed storage byte; otherwise item_size bytes are
 * copied at the linear offset.
 *
 * @param[in,out] ten     Allocated destination tensor.
 * @param[in]     idx     Logical element index.
 * @param[in]     pattern Raw bits to store (low bits used).
 */
inline void writeRaw(Tensor &ten, size_t idx, uint64_t pattern) {
  if (dtype_packing_factor(ten.dtype) == 2) {
    const auto nibble = static_cast<uint8_t>(pattern & 0xFU);
    uint8_t &byte = ten.data.data[idx / 2];
    byte = (idx % 2 == 0)
               ? static_cast<uint8_t>((byte & 0xF0U) | nibble)
               : static_cast<uint8_t>((byte & 0x0FU) | (nibble << 4));
    return;
  }
  std::memcpy(ten.data.data + (idx * ten.item_size), &pattern, ten.item_size);
}

/**
 * @brief Reads logical element @p idx zero-extended into a uint64_t.
 *
 * Packing-aware (low nibble first for Float4E2M1fn).
 *
 * @param[in] ten Allocated source tensor.
 * @param[in] idx Logical element index.
 * @return Raw element bits.
 */
[[nodiscard]] inline uint64_t readRaw(const Tensor &ten, size_t idx) {
  uint64_t out = 0;
  if (dtype_packing_factor(ten.dtype) == 2) {
    const uint8_t byte = ten.data.data[idx / 2];
    return (idx % 2 == 0) ? static_cast<uint64_t>(byte & 0x0FU)
                          : static_cast<uint64_t>((byte >> 4) & 0x0FU);
  }
  std::memcpy(&out, ten.data.data + (idx * ten.item_size), ten.item_size);
  return out;
}

/**
 * @brief Reads logical element @p idx reinterpreted as @p T (low bytes).
 *
 * @tparam T Integer type sized to the destination dtype.
 * @param[in] ten Allocated source tensor.
 * @param[in] idx Logical element index.
 * @return Element value.
 */
template <typename T>
[[nodiscard]] inline T readAs(const Tensor &ten, size_t idx) {
  static_assert(std::is_integral_v<T>);
  const uint64_t raw = readRaw(ten, idx);
  T out;
  std::memcpy(&out, &raw, sizeof(T));
  return out;
}

/**
 * @brief Writes a floating-point value into a float-dtype tensor element.
 *
 * Full-IEEE sources store the value natively (f32 after narrowing, f64
 * verbatim); reduced sources quantize through the reference encoder so the
 * exact stored pattern is known to the caller.
 *
 * @param[in,out] ten Allocated float-dtype tensor.
 * @param[in]     idx Logical element index.
 * @param[in]     v   Value to store.
 */
inline void writeFloatValue(Tensor &ten, size_t idx, double v) {
  switch (ten.dtype) {
  case DType_::Float32: {
    const float f = static_cast<float>(v);
    writeRaw(ten, idx, f32BitsOf(f));
    break;
  }
  case DType_::Float64: {
    uint64_t bits = 0;
    std::memcpy(&bits, &v, sizeof(bits));
    writeRaw(ten, idx, bits);
    break;
  }
  default:
    writeRaw(ten, idx, referenceEncode(specOf(ten.dtype), v));
    break;
  }
}

/**
 * @brief Reads logical element @p idx of a Float32 tensor as a float.
 *
 * @param[in] ten Allocated Float32 tensor.
 * @param[in] idx Logical element index.
 * @return Element value.
 */
[[nodiscard]] inline float readAsF32(const Tensor &ten, size_t idx) {
  const uint64_t raw = readRaw(ten, idx);
  float out = 0.0F;
  std::memcpy(&out, &raw, sizeof(out));
  return out;
}

/**
 * @brief Invokes @p f with the C integer type matching integer dtype @p d.
 *
 * @tparam F Callable accepting an explicit template parameter T (the C
 *         integer type); typically a templated lambda.
 * @param[in] d Integer dtype (Signed8..UnSigned64).
 * @param[in] f Callable to invoke.
 * @return Whatever @p f returns.
 */
template <typename F> decltype(auto) withIntType(DType_ d, F &&f) {
  switch (d) {
  case DType_::Signed8:
    return std::forward<F>(f).template operator()<int8_t>();
  case DType_::UnSigned8:
    return std::forward<F>(f).template operator()<uint8_t>();
  case DType_::Signed16:
    return std::forward<F>(f).template operator()<int16_t>();
  case DType_::UnSigned16:
    return std::forward<F>(f).template operator()<uint16_t>();
  case DType_::Signed32:
    return std::forward<F>(f).template operator()<int32_t>();
  case DType_::UnSigned32:
    return std::forward<F>(f).template operator()<uint32_t>();
  case DType_::Signed64:
    return std::forward<F>(f).template operator()<int64_t>();
  case DType_::UnSigned64:
    return std::forward<F>(f).template operator()<uint64_t>();
  default:
    ADD_FAILURE() << "withIntType: dtype " << static_cast<int>(d)
                  << " is not an integer dtype";
    return std::forward<F>(f).template operator()<int8_t>();
  }
}

/**
 * @brief Non-fatal element-wise comparison of two same-dtype tensors over
 *        the first @p logicalCount logical elements.
 *
 * @param[in]  a              First tensor.
 * @param[in]  b              Second tensor.
 * @param[in]  logicalCount   Number of logical elements to compare.
 * @param[out] firstMismatch  Receives the first differing index on failure.
 * @return True when identical over the compared range.
 */
[[nodiscard]] inline bool payloadEqual(const Tensor &a, const Tensor &b,
                                       size_t logicalCount,
                                       size_t *firstMismatch) {
  if (a.dtype != b.dtype) {
    ADD_FAILURE() << "payloadEqual: dtype mismatch";
    return false;
  }
  for (size_t i = 0; i < logicalCount; ++i) {
    if (readRaw(a, i) != readRaw(b, i)) {
      if (firstMismatch != nullptr) {
        *firstMismatch = i;
      }
      return false;
    }
  }
  return true;
}

/**
 * @brief Bitwise comparison of two same-dtype destinations that skips
 *        elements whose SOURCE pattern is NaN.
 *
 * NaN payload handling legitimately differs across conversion paths (the
 * scalar software path canonicalizes; hardware paths quiet), and the
 * project contract does not guarantee payload preservation. Everything
 * else, including infinities, must match bitwise.
 *
 * @param[in] src   Source tensor both destinations were converted from.
 * @param[in] a     First destination tensor.
 * @param[in] b     Second destination tensor.
 * @param[in] count Logical element count to compare.
 * @param[in] label Diagnostic tag prefixed to failure messages.
 */
inline void expectEqualSkippingSrcNan(const Tensor &src, const Tensor &a,
                                      const Tensor &b, size_t count,
                                      const std::string &label) {
  for (size_t i = 0; i < count; ++i) {
    if (isNaNPattern(src.dtype, readRaw(src, i))) {
      continue;
    }
    EXPECT_EQ(readRaw(a, i), readRaw(b, i)) << label << " element=" << i;
  }
}

/**
 * @brief Finds the registry entry for a dtype pair.
 *
 * @param[in] src Source dtype.
 * @param[in] dst Destination dtype.
 * @return Registry entry, or nullptr when the pair is unsupported.
 */
[[nodiscard]] inline const PairInfo *findPairFor(DType_ src, DType_ dst) {
  for (const auto &p : allPairs()) {
    if (p.src == src && p.dst == dst) {
      return &p;
    }
  }
  return nullptr;
}

/**
 * @brief Runs the portable scalar kernel of @p c's pair on @p c.
 *
 * @param[in,out] c Pair whose src/dt identify the kernel; dst is written.
 */
inline void runScalar(CastPair &c) {
  const PairInfo *p = findPairFor(c.src.getDType(), c.dst.getDType());
  if (p == nullptr) {
    ADD_FAILURE() << "runScalar: no registered pair";
    return;
  }
  p->scalar(&c.src.mutableCTensor(), &c.dst.mutableCTensor());
}

/**
 * @brief Runs the live dispatch wrapper of @p c's pair on @p c.
 *
 * @param[in,out] c Pair whose src/dt identify the kernel; dst is written.
 */
inline void runWrapper(CastPair &c) {
  const PairInfo *p = findPairFor(c.src.getDType(), c.dst.getDType());
  if (p == nullptr) {
    ADD_FAILURE() << "runWrapper: no registered pair";
    return;
  }
  p->wrapper(&c.src.mutableCTensor(), &c.dst.mutableCTensor());
}

/* ==========================================================================
 * Special-value pattern sets (declared independently per format)
 * ========================================================================== */

/// One named raw pattern for a floating dtype.
struct SpecialValue {
  const char *name; ///< Stable identifier for diagnostics.
  uint64_t pattern; ///< Raw storage pattern (zero-extended).
};

/**
 * @brief Canonical special-value patterns for one of the seven floating
 *        dtypes.
 *
 * Formats without inf/NaN simply omit those entries; FP4 omits NaN and Inf
 * entirely because it is a finite-only format. For Float8E4M3fn the "inf"
 * slots hold the saturation target (max finite) so policy tables can treat
 * every format uniformly.
 *
 * @param[in] d Floating dtype.
 * @return Named pattern list.
 */
inline std::vector<SpecialValue> specialValuesOf(DType_ d) {
  std::vector<SpecialValue> vals;
  switch (d) {
  case DType_::Float16:
    vals = {{.name = "zero_pos", .pattern = 0x0000},
            {.name = "zero_neg", .pattern = 0x8000},
            {.name = "qnan_pos", .pattern = 0x7E00},
            {.name = "qnan_neg", .pattern = 0xFE00},
            {.name = "inf_pos", .pattern = 0x7C00},
            {.name = "inf_neg", .pattern = 0xFC00},
            {.name = "min_sub", .pattern = 0x0001},
            {.name = "max_sub", .pattern = 0x03FF},
            {.name = "min_normal", .pattern = 0x0400},
            {.name = "max_finite", .pattern = 0x7BFF}};
    break;

  case DType_::BFloat16:
    vals = {{.name = "zero_pos", .pattern = 0x0000},
            {.name = "zero_neg", .pattern = 0x8000},
            {.name = "qnan_pos", .pattern = 0x7FC0},
            {.name = "qnan_neg", .pattern = 0xFFC0},
            {.name = "inf_pos", .pattern = 0x7F80},
            {.name = "inf_neg", .pattern = 0xFF80},
            {.name = "min_sub", .pattern = 0x0001},
            {.name = "max_sub", .pattern = 0x007F},
            {.name = "min_normal", .pattern = 0x0080},
            {.name = "max_finite", .pattern = 0x7F7F}};
    break;
  case DType_::Float8E4M3fn:
    vals = {{.name = "zero_pos", .pattern = 0x00},
            {.name = "zero_neg", .pattern = 0x80},
            {.name = "qnan_pos", .pattern = 0x7F},
            {.name = "qnan_neg", .pattern = 0xFF},
            // Saturation target: E4M3FN has no inf.
            {.name = "inf_pos", .pattern = 0x7E},
            {.name = "inf_neg", .pattern = 0xFE},
            {.name = "min_sub", .pattern = 0x01},
            {.name = "max_sub", .pattern = 0x07},
            {.name = "min_normal", .pattern = 0x08},
            {.name = "max_finite", .pattern = 0x7E}};
    break;
  case DType_::Float8E5M2:
    vals = {{.name = "zero_pos", .pattern = 0x00},
            {.name = "zero_neg", .pattern = 0x80},
            {.name = "qnan_pos", .pattern = 0x7F},
            {.name = "qnan_neg", .pattern = 0xFF},
            {.name = "inf_pos", .pattern = 0x7C},
            {.name = "inf_neg", .pattern = 0xFC},
            {.name = "min_sub", .pattern = 0x01},
            {.name = "max_sub", .pattern = 0x03},
            {.name = "min_normal", .pattern = 0x04},
            {.name = "max_finite", .pattern = 0x7B}};
    break;
  case DType_::Float4E2M1fn:
    vals = {{.name = "zero_pos", .pattern = 0x0},
            {.name = "zero_neg", .pattern = 0x8},
            {.name = "max_mag", .pattern = 0x7},
            {.name = "max_mag_neg", .pattern = 0xF},
            {.name = "min_sub", .pattern = 0x1},
            {.name = "min_sub_neg", .pattern = 0x9},
            {.name = "min_normal", .pattern = 0x2}};
    break;
  default:
    if (d == DType_::Float32) {
      vals = {{.name = "zero_pos", .pattern = 0x00000000U},
              {.name = "zero_neg", .pattern = 0x80000000U},
              {.name = "qnan_pos", .pattern = 0x7FC00000U},
              {.name = "qnan_neg", .pattern = 0xFFC00000U},
              {.name = "inf_pos", .pattern = 0x7F800000U},
              {.name = "inf_neg", .pattern = 0xFF800000U},
              {.name = "min_sub", .pattern = 0x00000001U},
              {.name = "max_sub", .pattern = 0x007FFFFFU},
              {.name = "min_normal", .pattern = 0x00800000U},
              {.name = "max_finite", .pattern = 0x7F7FFFFFU}};
    } else {
      vals = {{.name = "zero_pos", .pattern = 0x0000000000000000ULL},
              {.name = "zero_neg", .pattern = 0x8000000000000000ULL},
              {.name = "qnan_pos", .pattern = 0x7FF8000000000000ULL},
              {.name = "qnan_neg", .pattern = 0xFFF8000000000000ULL},
              {.name = "inf_pos", .pattern = 0x7FF0000000000000ULL},
              {.name = "inf_neg", .pattern = 0xFFF0000000000000ULL},
              {.name = "min_sub", .pattern = 0x0000000000000001ULL},
              {.name = "max_sub", .pattern = 0x000FFFFFFFFFFFFFULL},
              {.name = "min_normal", .pattern = 0x0010000000000000ULL},
              {.name = "max_finite", .pattern = 0x7FEFFFFFFFFFFFFFULL}};
    }
    break;
  }
  return vals;
}

/* ==========================================================================
 * ISA gating: evaluates cast_tables.h "Requires:" strings against the live
 * capability flags. get_simd_capabilities() is a cached singleton, so
 * capabilities cannot be injected synthetically; direct invocation of a SIMD
 * variant must therefore be gated on real host support.
 * ========================================================================== */

/**
 * @brief True when the host supports every ISA named in @p requirements.
 *
 * Grammar mirrors the cast_tables.h documentation: a comma-separated AND
 * list of tokens where "AVX/AVX2" means AVX OR AVX2. Recognized tokens:
 * SSE4.2, AVX, AVX2, F16C, AVX512F, AVX512BW, AVX512DQ, AVX512VL,
 * AVX512FP16, AVX512BF16.
 *
 * @param[in] requirements Requirement string from cast_tables.h.
 * @param[in] caps         Live capability flags.
 * @return True when every requirement is satisfied.
 */
[[nodiscard]] inline bool isaSupported(std::string_view requirements,
                                       const SIMDCapabilities &caps) {
  size_t pos = 0;
  while (pos < requirements.size()) {
    const size_t comma = requirements.find(',', pos);
    const std::string_view token = requirements.substr(
        pos,
        comma == std::string_view::npos ? std::string_view::npos : comma - pos);
    pos = (comma == std::string_view::npos) ? requirements.size() : comma + 1;

    size_t begin = 0;
    while (begin < token.size() &&
           (token[begin] == ' ' || token[begin] == '\t')) {
      ++begin;
    }
    size_t end = token.size();
    while (end > begin && (token[end - 1] == ' ' || token[end - 1] == '\t')) {
      --end;
    }
    const std::string_view t = token.substr(begin, end - begin);

    bool supported = false;
    if (t == "SSE4.2") {
      supported = caps.sse4_2_;
    } else if (t == "AVX/AVX2") {
      supported = caps.avx_ || caps.avx2_;
    } else if (t == "AVX") {
      supported = caps.avx_;
    } else if (t == "AVX2") {
      supported = caps.avx2_;
    } else if (t == "F16C") {
      supported = caps.f16c_;
    } else if (t == "AVX512F") {
      supported = caps.avx512f_;
    } else if (t == "AVX512BW") {
      supported = caps.avx512_bw_;
    } else if (t == "AVX512DQ") {
      supported = caps.avx512_dq_;
    } else if (t == "AVX512VL") {
      supported = caps.avx512_vl_;
    } else if (t == "AVX512FP16") {
      supported = caps.avx512_fp16_;
    } else if (t == "AVX512BF16") {
      supported = caps.avx512_bf16_;
    } else {
      ADD_FAILURE() << "isaSupported: unknown requirement token '" << t
                    << "' in \"" << requirements << "\"";
      return false;
    }
    if (!supported) {
      return false;
    }
  }
  return true;
}

/**
 * @brief Live capability snapshot accessor.
 *
 * @return Read-only view of the process capability singleton.
 */
inline const SIMDCapabilities &hostCaps() { return *get_simd_capabilities(); }

} // namespace tests::casting
