//! Global registry for managing storage instances.
//!
//! The registry is process-wide and guarded by a [`Mutex`]. All operations
//! take the lock before accessing a [`RustStorage`], so the storage object is
//! never concurrently mutated by two registry operations. Callers must still
//! obey the handle lifecycle contract: a handle must remain registered while
//! it is being queried, resized, retained, or released.

use crate::error::StorageError;
use crate::storage::RustStorage;
use std::collections::HashMap;
use std::sync::{Mutex, OnceLock};

static MANAGER: OnceLock<Mutex<HashMap<u64, RustStorage>>> = OnceLock::new();

/// Returns the lazily initialized process-wide storage registry.
fn registry() -> &'static Mutex<HashMap<u64, RustStorage>> {
    MANAGER.get_or_init(|| Mutex::new(HashMap::new()))
}

/// Manages the process-wide mapping from handle IDs to storage objects.
///
/// This is a namespace type; it has no instance state and must not be
/// constructed. The methods serialize access to the registry through its
/// internal mutex.
pub struct StorageManager;

impl StorageManager {
    /// Inserts a newly allocated storage object into the registry.
    ///
    /// The caller transfers ownership of `storage` to the registry. IDs are
    /// generated by [`crate::id::next_id`], so replacing an existing entry is
    /// not expected during normal operation.
    ///
    /// # Errors
    ///
    /// Returns [`StorageError::ManagerPoisoned`] when the registry mutex is
    /// poisoned.
    pub fn insert(id: u64, storage: RustStorage) -> Result<(), StorageError> {
        registry()
            .lock()
            .map_err(|_| StorageError::ManagerPoisoned)?
            .insert(id, storage);
        Ok(())
    }

    /// Applies a closure to the storage registered under `id`.
    ///
    /// The closure runs while the registry mutex is held and receives
    /// exclusive access to the storage. It must not call another
    /// [`StorageManager`] method, because doing so would attempt to acquire
    /// the same non-reentrant mutex again.
    ///
    /// # Errors
    ///
    /// Returns [`StorageError::InvalidHandle`] when `id` is not registered or
    /// [`StorageError::ManagerPoisoned`] when the registry mutex is poisoned.
    pub fn with<F, R>(id: u64, f: F) -> Result<R, StorageError>
    where
        F: FnOnce(&mut RustStorage) -> R,
    {
        registry()
            .lock()
            .map_err(|_| StorageError::ManagerPoisoned)?
            .get_mut(&id)
            .map(f)
            .ok_or(StorageError::InvalidHandle)
    }

    /// Releases one reference to the storage registered under `id`.
    ///
    /// If the reference count remains above zero, the storage stays in the
    /// registry and the function returns `Ok(false)`. On the final release,
    /// the allocation is explicitly deallocated before the registry entry is
    /// removed and the function returns `Ok(true)`.
    ///
    /// If deallocation fails, the reference count is restored and the entry
    /// remains registered so the caller can report the error or retry.
    ///
    /// # Errors
    ///
    /// Returns [`StorageError::InvalidHandle`] when `id` is not registered,
    /// [`StorageError::ManagerPoisoned`] when the registry mutex is poisoned,
    /// or a backend error when final deallocation fails.
    pub fn release(id: u64) -> Result<bool, StorageError> {
        let mut map = registry()
            .lock()
            .map_err(|_| StorageError::ManagerPoisoned)?;
        let storage: &mut RustStorage = map.get_mut(&id).ok_or(StorageError::InvalidHandle)?;

        if !storage.decrement_ref()? {
            return Ok(false);
        }

        if let Err(error) = storage.deallocate() {
            storage.increment_ref()?;
            return Err(error);
        }

        map.remove(&id);
        Ok(true)
    }

    /// Returns `true` if the registry currently contains `id`.
    ///
    /// A poisoned registry is treated as unavailable and therefore returns
    /// `false`.
    pub fn contains(id: u64) -> bool {
        registry()
            .lock()
            .map(|map| map.contains_key(&id))
            .unwrap_or(false)
    }
}
