/**
 * @file cast_tables.c
 *
 * @warning *** DO NOT EDIT THIS FILE – GENERATED CODE ***
 *
 * This file was generated automatically by the NovaNN code-generation
 * pipeline.  All manual edits will be overwritten on the next run.
 *
 * To change the output you must edit one of the upstream sources:
 *   - Template   : tools/codegen/templates/.../CastTables.jinja
 *   - Rules      : tools/codegen/rules/.../cast_tables_rules.json
 *   - Generator  : tools/codegen/scripts/.../gen_cast_tables.py
 *
 * @brief Dispatch tables for CPU dtype casting.
 *
 * Each lookup table lists available implementations in descending
 * capability order. SIMD-backed tables are wrapped in _GNUC_CLANG_
 * so MSVC falls back to the scalar implementation only.
 */

#include <ncore/headeronly/macros.h>
#include <ncore/native/cpu/dtype/casting.h>
#include <ncore/tables/cast_tables.h>

/* =========================================================================
 * Dispatch tables — lists implementations in descending capability order
 * ========================================================================= */

/**
 * @brief Dispatch table for float4_e2m1fn_x2 to float8_e4m3fn conversions.
 *
 * Variants:
 * - Index 0: tfp4e2m1_to_fp8e4m3_scalar() — Portable fallback
 */
const CastFn lookup_tfp4e2m1_to_fp8e4m3[] = {tfp4e2m1_to_fp8e4m3_scalar};

/**
 * @brief Dispatch table for float4_e2m1fn_x2 to float8_e5m2 conversions.
 *
 * Variants:
 * - Index 0: tfp4e2m1_to_fp8e5m2_scalar() — Portable fallback
 */
const CastFn lookup_tfp4e2m1_to_fp8e5m2[] = {tfp4e2m1_to_fp8e5m2_scalar};

/**
 * @brief Dispatch table for float4_e2m1fn_x2 to float16 conversions.
 *
 * Variants:
 * - Index 0: tfp4e2m1_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_tfp4e2m1_to_fp16[] = {tfp4e2m1_to_fp16_scalar};

/**
 * @brief Dispatch table for float4_e2m1fn_x2 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: tfp4e2m1_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_tfp4e2m1_to_bf16[] = {tfp4e2m1_to_bf16_scalar};

/**
 * @brief Dispatch table for float4_e2m1fn_x2 to float conversions.
 *
 * Variants:
 * - Index 0: tfp4e2m1_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_tfp4e2m1_to_f32[] = {tfp4e2m1_to_f32_scalar};

/**
 * @brief Dispatch table for float4_e2m1fn_x2 to double conversions.
 *
 * Variants:
 * - Index 0: tfp4e2m1_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_tfp4e2m1_to_f64[] = {tfp4e2m1_to_f64_scalar};

/**
 * @brief Dispatch table for float8_e4m3fn to float4_e2m1fn_x2 conversions.
 *
 * Variants:
 * - Index 0: tfp8e4m3_to_fp4e2m1_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e4m3_to_fp4e2m1[] = {tfp8e4m3_to_fp4e2m1_scalar};

/**
 * @brief Dispatch table for float8_e4m3fn to float8_e5m2 conversions.
 *
 * Variants:
 * - Index 0: tfp8e4m3_to_fp8e5m2_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e4m3_to_fp8e5m2[] = {tfp8e4m3_to_fp8e5m2_scalar};

/**
 * @brief Dispatch table for float8_e4m3fn to float16 conversions.
 *
 * Variants:
 * - Index 0: tfp8e4m3_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e4m3_to_fp16[] = {tfp8e4m3_to_fp16_scalar};

/**
 * @brief Dispatch table for float8_e4m3fn to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: tfp8e4m3_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e4m3_to_bf16[] = {tfp8e4m3_to_bf16_scalar};

/**
 * @brief Dispatch table for float8_e4m3fn to float conversions.
 *
 * Variants:
 * - Index 0: tfp8e4m3_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e4m3_to_f32[] = {tfp8e4m3_to_f32_scalar};

/**
 * @brief Dispatch table for float8_e4m3fn to double conversions.
 *
 * Variants:
 * - Index 0: tfp8e4m3_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e4m3_to_f64[] = {tfp8e4m3_to_f64_scalar};

/**
 * @brief Dispatch table for float8_e5m2 to float4_e2m1fn_x2 conversions.
 *
 * Variants:
 * - Index 0: tfp8e5m2_to_fp4e2m1_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e5m2_to_fp4e2m1[] = {tfp8e5m2_to_fp4e2m1_scalar};

/**
 * @brief Dispatch table for float8_e5m2 to float8_e4m3fn conversions.
 *
 * Variants:
 * - Index 0: tfp8e5m2_to_fp8e4m3_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e5m2_to_fp8e4m3[] = {tfp8e5m2_to_fp8e4m3_scalar};

/**
 * @brief Dispatch table for float8_e5m2 to float16 conversions.
 *
 * Variants:
 * - Index 0: tfp8e5m2_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e5m2_to_fp16[] = {tfp8e5m2_to_fp16_scalar};

/**
 * @brief Dispatch table for float8_e5m2 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: tfp8e5m2_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e5m2_to_bf16[] = {tfp8e5m2_to_bf16_scalar};

/**
 * @brief Dispatch table for float8_e5m2 to float conversions.
 *
 * Variants:
 * - Index 0: tfp8e5m2_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e5m2_to_f32[] = {tfp8e5m2_to_f32_scalar};

/**
 * @brief Dispatch table for float8_e5m2 to double conversions.
 *
 * Variants:
 * - Index 0: tfp8e5m2_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e5m2_to_f64[] = {tfp8e5m2_to_f64_scalar};

/**
 * @brief Dispatch table for float16 to float4_e2m1fn_x2 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_fp4e2m1_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_fp4e2m1[] = {tfp16_to_fp4e2m1_scalar};

/**
 * @brief Dispatch table for float16 to float8_e4m3fn conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_fp8e4m3_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_fp8e4m3[] = {tfp16_to_fp8e4m3_scalar};

/**
 * @brief Dispatch table for float16 to float8_e5m2 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_fp8e5m2_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_fp8e5m2[] = {tfp16_to_fp8e5m2_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float16 to float conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_f32_avx512() — Requires: AVX512F
 * - Index 1: tfp16_to_f32_avx_avx2_fp16c() — Requires: AVX/AVX2, F16C
 * - Index 2: tfp16_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_f32[] = {
    tfp16_to_f32_avx512, tfp16_to_f32_avx_avx2_fp16c, tfp16_to_f32_scalar};
#else
/**
 * @brief Dispatch table for float16 to float conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_f32[] = {tfp16_to_f32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float16 to double conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_f64_avx512() — Requires: AVX512F, AVX512FP16
 * - Index 1: tfp16_to_f64_avx_avx2_fp16c() — Requires: F16C
 * - Index 2: tfp16_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_f64[] = {
    tfp16_to_f64_avx512, tfp16_to_f64_avx_avx2_fp16c, tfp16_to_f64_scalar};
#else
/**
 * @brief Dispatch table for float16 to double conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_f64[] = {tfp16_to_f64_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float16 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_bf16_avx512bf16() — Requires: AVX512F, AVX512BF16
 * - Index 1: tfp16_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_bf16[] = {tfp16_to_bf16_avx512bf16,
                                       tfp16_to_bf16_scalar};
#else
/**
 * @brief Dispatch table for float16 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_bf16[] = {tfp16_to_bf16_scalar};
#endif

/**
 * @brief Dispatch table for float to float4_e2m1fn_x2 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_fp4e2m1_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_fp4e2m1[] = {tf32_to_fp4e2m1_scalar};

/**
 * @brief Dispatch table for float to float8_e4m3fn conversions.
 *
 * Variants:
 * - Index 0: tf32_to_fp8e4m3_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_fp8e4m3[] = {tf32_to_fp8e4m3_scalar};

/**
 * @brief Dispatch table for float to float8_e5m2 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_fp8e5m2_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_fp8e5m2[] = {tf32_to_fp8e5m2_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float to float16 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_fp16_avx512fp16() — Requires: AVX512F, AVX512FP16
 * - Index 1: tf32_to_fp16_avx_avx2_f16c() — Requires: F16C
 * - Index 2: tf32_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_fp16[] = {
    tf32_to_fp16_avx512fp16, tf32_to_fp16_avx_avx2_f16c, tf32_to_fp16_scalar};
#else
/**
 * @brief Dispatch table for float to float16 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_fp16[] = {tf32_to_fp16_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float to double conversions.
 *
 * Variants:
 * - Index 0: tf32_to_f64_avx512() — Requires: AVX512F
 * - Index 1: tf32_to_f64_avx_avx2() — Requires: AVX/AVX2
 * - Index 2: tf32_to_f64_sse4_2() — Requires: SSE4.2
 * - Index 3: tf32_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_f64[] = {tf32_to_f64_avx512, tf32_to_f64_avx_avx2,
                                     tf32_to_f64_sse4_2, tf32_to_f64_scalar};
#else
/**
 * @brief Dispatch table for float to double conversions.
 *
 * Variants:
 * - Index 0: tf32_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_f64[] = {tf32_to_f64_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_bf16_avx512bf16() — Requires: AVX512F, AVX512BF16,
 * AVX512BW, AVX512VL
 * - Index 1: tf32_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_bf16[] = {tf32_to_bf16_avx512bf16,
                                      tf32_to_bf16_scalar};
#else
/**
 * @brief Dispatch table for float to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_bf16[] = {tf32_to_bf16_scalar};
#endif

/**
 * @brief Dispatch table for bfloat16 to float4_e2m1fn_x2 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_fp4e2m1_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_fp4e2m1[] = {tbf16_to_fp4e2m1_scalar};

/**
 * @brief Dispatch table for bfloat16 to float8_e4m3fn conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_fp8e4m3_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_fp8e4m3[] = {tbf16_to_fp8e4m3_scalar};

/**
 * @brief Dispatch table for bfloat16 to float8_e5m2 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_fp8e5m2_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_fp8e5m2[] = {tbf16_to_fp8e5m2_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for bfloat16 to float16 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_fp16_avx512bf16_fp16() — Requires: AVX512F, AVX512BF16,
 * AVX512FP16
 * - Index 1: tbf16_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_fp16[] = {tbf16_to_fp16_avx512bf16_fp16,
                                       tbf16_to_fp16_scalar};
#else
/**
 * @brief Dispatch table for bfloat16 to float16 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_fp16[] = {tbf16_to_fp16_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for bfloat16 to float conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_f32_avx512bf16() — Requires: AVX512BF16, AVX512F
 * - Index 1: tbf16_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_f32[] = {tbf16_to_f32_avx512bf16,
                                      tbf16_to_f32_scalar};
#else
/**
 * @brief Dispatch table for bfloat16 to float conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_f32[] = {tbf16_to_f32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for bfloat16 to double conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_f64_avx512bf16() — Requires: AVX512F, AVX512BF16,
 * AVX512VL
 * - Index 1: tbf16_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_f64[] = {tbf16_to_f64_avx512bf16,
                                      tbf16_to_f64_scalar};
#else
/**
 * @brief Dispatch table for bfloat16 to double conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_f64[] = {tbf16_to_f64_scalar};
#endif

/**
 * @brief Dispatch table for double to float4_e2m1fn_x2 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_fp4e2m1_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_fp4e2m1[] = {tf64_to_fp4e2m1_scalar};

/**
 * @brief Dispatch table for double to float8_e4m3fn conversions.
 *
 * Variants:
 * - Index 0: tf64_to_fp8e4m3_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_fp8e4m3[] = {tf64_to_fp8e4m3_scalar};

/**
 * @brief Dispatch table for double to float8_e5m2 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_fp8e5m2_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_fp8e5m2[] = {tf64_to_fp8e5m2_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for double to float16 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_fp16_avx512fp16() — Requires: AVX512F, AVX512FP16
 * - Index 1: tf64_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_fp16[] = {tf64_to_fp16_avx512fp16,
                                      tf64_to_fp16_scalar};
#else
/**
 * @brief Dispatch table for double to float16 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_fp16[] = {tf64_to_fp16_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for double to float conversions.
 *
 * Variants:
 * - Index 0: tf64_to_f32_avx512() — Requires: AVX512F
 * - Index 1: tf64_to_f32_avx_avx2() — Requires: AVX/AVX2
 * - Index 2: tf64_to_f32_sse4_2() — Requires: SSE4.2
 * - Index 3: tf64_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_f32[] = {tf64_to_f32_avx512, tf64_to_f32_avx_avx2,
                                     tf64_to_f32_sse4_2, tf64_to_f32_scalar};
#else
/**
 * @brief Dispatch table for double to float conversions.
 *
 * Variants:
 * - Index 0: tf64_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_f32[] = {tf64_to_f32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for double to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_bf16_avx512bf16() — Requires: AVX512F, AVX512BF16,
 * AVX512VL
 * - Index 1: tf64_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_bf16[] = {tf64_to_bf16_avx512bf16,
                                      tf64_to_bf16_scalar};
#else
/**
 * @brief Dispatch table for double to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_bf16[] = {tf64_to_bf16_scalar};
#endif

/**
 * @brief Dispatch table for float4_e2m1fn_x2 to int8 conversions.
 *
 * Variants:
 * - Index 0: tfp4e2m1_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tfp4e2m1_to_s8[] = {tfp4e2m1_to_s8_scalar};

/**
 * @brief Dispatch table for float4_e2m1fn_x2 to int16 conversions.
 *
 * Variants:
 * - Index 0: tfp4e2m1_to_s16_scalar() — Portable fallback
 */
const CastFn lookup_tfp4e2m1_to_s16[] = {tfp4e2m1_to_s16_scalar};

/**
 * @brief Dispatch table for float4_e2m1fn_x2 to int32 conversions.
 *
 * Variants:
 * - Index 0: tfp4e2m1_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tfp4e2m1_to_s32[] = {tfp4e2m1_to_s32_scalar};

/**
 * @brief Dispatch table for float4_e2m1fn_x2 to int64 conversions.
 *
 * Variants:
 * - Index 0: tfp4e2m1_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tfp4e2m1_to_s64[] = {tfp4e2m1_to_s64_scalar};

/**
 * @brief Dispatch table for float8_e4m3fn to int8 conversions.
 *
 * Variants:
 * - Index 0: tfp8e4m3_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e4m3_to_s8[] = {tfp8e4m3_to_s8_scalar};

/**
 * @brief Dispatch table for float8_e4m3fn to int16 conversions.
 *
 * Variants:
 * - Index 0: tfp8e4m3_to_s16_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e4m3_to_s16[] = {tfp8e4m3_to_s16_scalar};

/**
 * @brief Dispatch table for float8_e4m3fn to int32 conversions.
 *
 * Variants:
 * - Index 0: tfp8e4m3_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e4m3_to_s32[] = {tfp8e4m3_to_s32_scalar};

/**
 * @brief Dispatch table for float8_e4m3fn to int64 conversions.
 *
 * Variants:
 * - Index 0: tfp8e4m3_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e4m3_to_s64[] = {tfp8e4m3_to_s64_scalar};

/**
 * @brief Dispatch table for float8_e5m2 to int8 conversions.
 *
 * Variants:
 * - Index 0: tfp8e5m2_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e5m2_to_s8[] = {tfp8e5m2_to_s8_scalar};

/**
 * @brief Dispatch table for float8_e5m2 to int16 conversions.
 *
 * Variants:
 * - Index 0: tfp8e5m2_to_s16_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e5m2_to_s16[] = {tfp8e5m2_to_s16_scalar};

/**
 * @brief Dispatch table for float8_e5m2 to int32 conversions.
 *
 * Variants:
 * - Index 0: tfp8e5m2_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e5m2_to_s32[] = {tfp8e5m2_to_s32_scalar};

/**
 * @brief Dispatch table for float8_e5m2 to int64 conversions.
 *
 * Variants:
 * - Index 0: tfp8e5m2_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e5m2_to_s64[] = {tfp8e5m2_to_s64_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float16 to int8 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_s8_avx512fp16() — Requires: AVX512FP16, AVX512BW,
 * AVX512F, AVX512VL
 * - Index 1: tfp16_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_s8[] = {tfp16_to_s8_avx512fp16,
                                     tfp16_to_s8_scalar};
#else
/**
 * @brief Dispatch table for float16 to int8 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_s8[] = {tfp16_to_s8_scalar};
#endif

/**
 * @brief Dispatch table for float16 to int16 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_s16_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_s16[] = {tfp16_to_s16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float16 to int32 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_s32_avx512fp16() — Requires: AVX512FP16, AVX512F,
 * AVX512VL
 * - Index 1: tfp16_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_s32[] = {tfp16_to_s32_avx512fp16,
                                      tfp16_to_s32_scalar};
#else
/**
 * @brief Dispatch table for float16 to int32 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_s32[] = {tfp16_to_s32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float16 to int64 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_s64_avx512fp16() — Requires: AVX512F, AVX512FP16,
 * AVX512VL
 * - Index 1: tfp16_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_s64[] = {tfp16_to_s64_avx512fp16,
                                      tfp16_to_s64_scalar};
#else
/**
 * @brief Dispatch table for float16 to int64 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_s64[] = {tfp16_to_s64_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float to int8 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_s8_avx512() — Requires: AVX512F, AVX512BW
 * - Index 1: tf32_to_s8_avx2() — Requires: AVX2
 * - Index 2: tf32_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_s8[] = {tf32_to_s8_avx512, tf32_to_s8_avx2,
                                    tf32_to_s8_scalar};
#else
/**
 * @brief Dispatch table for float to int8 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_s8[] = {tf32_to_s8_scalar};
#endif

/**
 * @brief Dispatch table for float to int16 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_s16_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_s16[] = {tf32_to_s16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float to int32 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_s32_avx512() — Requires: AVX512F
 * - Index 1: tf32_to_s32_avx2() — Requires: AVX2
 * - Index 2: tf32_to_s32_sse4_2() — Requires: SSE4.2
 * - Index 3: tf32_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_s32[] = {tf32_to_s32_avx512, tf32_to_s32_avx2,
                                     tf32_to_s32_sse4_2, tf32_to_s32_scalar};
#else
/**
 * @brief Dispatch table for float to int32 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_s32[] = {tf32_to_s32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float to int64 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_s64_avx512() — Requires: AVX512F, AVX512DQ, AVX512VL
 * - Index 1: tf32_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_s64[] = {tf32_to_s64_avx512, tf32_to_s64_scalar};
#else
/**
 * @brief Dispatch table for float to int64 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_s64[] = {tf32_to_s64_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for bfloat16 to int8 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_s8_avx512bf16() — Requires: AVX512BF16, AVX512BW, AVX512F
 * - Index 1: tbf16_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_s8[] = {tbf16_to_s8_avx512bf16,
                                     tbf16_to_s8_scalar};
#else
/**
 * @brief Dispatch table for bfloat16 to int8 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_s8[] = {tbf16_to_s8_scalar};
#endif

/**
 * @brief Dispatch table for bfloat16 to int16 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_s16_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_s16[] = {tbf16_to_s16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for bfloat16 to int32 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_s32_avx512bf16() — Requires: AVX512BF16, AVX512F
 * - Index 1: tbf16_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_s32[] = {tbf16_to_s32_avx512bf16,
                                      tbf16_to_s32_scalar};
#else
/**
 * @brief Dispatch table for bfloat16 to int32 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_s32[] = {tbf16_to_s32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for bfloat16 to int64 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_s64_avx512bf16() — Requires: AVX512F, AVX512BF16,
 * AVX512VL, AVX512DQ
 * - Index 1: tbf16_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_s64[] = {tbf16_to_s64_avx512bf16,
                                      tbf16_to_s64_scalar};
#else
/**
 * @brief Dispatch table for bfloat16 to int64 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_s64[] = {tbf16_to_s64_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for double to int8 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_s8_avx512() — Requires: AVX512F
 * - Index 1: tf64_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_s8[] = {tf64_to_s8_avx512, tf64_to_s8_scalar};
#else
/**
 * @brief Dispatch table for double to int8 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_s8[] = {tf64_to_s8_scalar};
#endif

/**
 * @brief Dispatch table for double to int16 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_s16_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_s16[] = {tf64_to_s16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for double to int32 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_s32_avx512() — Requires: AVX512F
 * - Index 1: tf64_to_s32_avx_avx2() — Requires: AVX/AVX2
 * - Index 2: tf64_to_s32_sse4_2() — Requires: SSE4.2
 * - Index 3: tf64_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_s32[] = {tf64_to_s32_avx512, tf64_to_s32_avx_avx2,
                                     tf64_to_s32_sse4_2, tf64_to_s32_scalar};
#else
/**
 * @brief Dispatch table for double to int32 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_s32[] = {tf64_to_s32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for double to int64 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_s64_avx512() — Requires: AVX512F, AVX512DQ
 * - Index 1: tf64_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_s64[] = {tf64_to_s64_avx512, tf64_to_s64_scalar};
#else
/**
 * @brief Dispatch table for double to int64 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_s64[] = {tf64_to_s64_scalar};
#endif

/**
 * @brief Dispatch table for float4_e2m1fn_x2 to uint8 conversions.
 *
 * Variants:
 * - Index 0: tfp4e2m1_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_tfp4e2m1_to_u8[] = {tfp4e2m1_to_u8_scalar};

/**
 * @brief Dispatch table for float4_e2m1fn_x2 to uint16 conversions.
 *
 * Variants:
 * - Index 0: tfp4e2m1_to_u16_scalar() — Portable fallback
 */
const CastFn lookup_tfp4e2m1_to_u16[] = {tfp4e2m1_to_u16_scalar};

/**
 * @brief Dispatch table for float4_e2m1fn_x2 to uint32 conversions.
 *
 * Variants:
 * - Index 0: tfp4e2m1_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_tfp4e2m1_to_u32[] = {tfp4e2m1_to_u32_scalar};

/**
 * @brief Dispatch table for float4_e2m1fn_x2 to uint64 conversions.
 *
 * Variants:
 * - Index 0: tfp4e2m1_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_tfp4e2m1_to_u64[] = {tfp4e2m1_to_u64_scalar};

/**
 * @brief Dispatch table for float8_e4m3fn to uint8 conversions.
 *
 * Variants:
 * - Index 0: tfp8e4m3_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e4m3_to_u8[] = {tfp8e4m3_to_u8_scalar};

/**
 * @brief Dispatch table for float8_e4m3fn to uint16 conversions.
 *
 * Variants:
 * - Index 0: tfp8e4m3_to_u16_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e4m3_to_u16[] = {tfp8e4m3_to_u16_scalar};

/**
 * @brief Dispatch table for float8_e4m3fn to uint32 conversions.
 *
 * Variants:
 * - Index 0: tfp8e4m3_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e4m3_to_u32[] = {tfp8e4m3_to_u32_scalar};

/**
 * @brief Dispatch table for float8_e4m3fn to uint64 conversions.
 *
 * Variants:
 * - Index 0: tfp8e4m3_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e4m3_to_u64[] = {tfp8e4m3_to_u64_scalar};

/**
 * @brief Dispatch table for float8_e5m2 to uint8 conversions.
 *
 * Variants:
 * - Index 0: tfp8e5m2_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e5m2_to_u8[] = {tfp8e5m2_to_u8_scalar};

/**
 * @brief Dispatch table for float8_e5m2 to uint16 conversions.
 *
 * Variants:
 * - Index 0: tfp8e5m2_to_u16_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e5m2_to_u16[] = {tfp8e5m2_to_u16_scalar};

/**
 * @brief Dispatch table for float8_e5m2 to uint32 conversions.
 *
 * Variants:
 * - Index 0: tfp8e5m2_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e5m2_to_u32[] = {tfp8e5m2_to_u32_scalar};

/**
 * @brief Dispatch table for float8_e5m2 to uint64 conversions.
 *
 * Variants:
 * - Index 0: tfp8e5m2_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_tfp8e5m2_to_u64[] = {tfp8e5m2_to_u64_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float16 to uint8 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_u8_avx512fp16() — Requires: AVX512F, AVX512FP16,
 * AVX512BW, AVX512VL
 * - Index 1: tfp16_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_u8[] = {tfp16_to_u8_avx512fp16,
                                     tfp16_to_u8_scalar};
#else
/**
 * @brief Dispatch table for float16 to uint8 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_u8[] = {tfp16_to_u8_scalar};
#endif

/**
 * @brief Dispatch table for float16 to uint16 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_u16_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_u16[] = {tfp16_to_u16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float16 to uint32 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_u32_avx512fp16() — Requires: AVX512F, AVX512FP16,
 * AVX512VL
 * - Index 1: tfp16_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_u32[] = {tfp16_to_u32_avx512fp16,
                                      tfp16_to_u32_scalar};
#else
/**
 * @brief Dispatch table for float16 to uint32 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_u32[] = {tfp16_to_u32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float16 to uint64 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_u64_avx512fp16() — Requires: AVX512F, AVX512FP16,
 * AVX512VL
 * - Index 1: tfp16_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_u64[] = {tfp16_to_u64_avx512fp16,
                                      tfp16_to_u64_scalar};
#else
/**
 * @brief Dispatch table for float16 to uint64 conversions.
 *
 * Variants:
 * - Index 0: tfp16_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_tfp16_to_u64[] = {tfp16_to_u64_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float to uint8 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_u8_avx512() — Requires: AVX512F, AVX512BW, AVX512VL
 * - Index 1: tf32_to_u8_avx2() — Requires: AVX2
 * - Index 2: tf32_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_u8[] = {tf32_to_u8_avx512, tf32_to_u8_avx2,
                                    tf32_to_u8_scalar};
#else
/**
 * @brief Dispatch table for float to uint8 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_u8[] = {tf32_to_u8_scalar};
#endif

/**
 * @brief Dispatch table for float to uint16 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_u16_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_u16[] = {tf32_to_u16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float to uint32 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_u32_avx512() — Requires: AVX512F
 * - Index 1: tf32_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_u32[] = {tf32_to_u32_avx512, tf32_to_u32_scalar};
#else
/**
 * @brief Dispatch table for float to uint32 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_u32[] = {tf32_to_u32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for float to uint64 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_u64_avx512() — Requires: AVX512F, AVX512DQ, AVX512VL
 * - Index 1: tf32_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_u64[] = {tf32_to_u64_avx512, tf32_to_u64_scalar};
#else
/**
 * @brief Dispatch table for float to uint64 conversions.
 *
 * Variants:
 * - Index 0: tf32_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_tf32_to_u64[] = {tf32_to_u64_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for bfloat16 to uint8 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_u8_avx512bf16() — Requires: AVX512BF16, AVX512BW, AVX512F
 * - Index 1: tbf16_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_u8[] = {tbf16_to_u8_avx512bf16,
                                     tbf16_to_u8_scalar};
#else
/**
 * @brief Dispatch table for bfloat16 to uint8 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_u8[] = {tbf16_to_u8_scalar};
#endif

/**
 * @brief Dispatch table for bfloat16 to uint16 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_u16_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_u16[] = {tbf16_to_u16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for bfloat16 to uint32 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_u32_avx512bf16() — Requires: AVX512BF16, AVX512F
 * - Index 1: tbf16_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_u32[] = {tbf16_to_u32_avx512bf16,
                                      tbf16_to_u32_scalar};
#else
/**
 * @brief Dispatch table for bfloat16 to uint32 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_u32[] = {tbf16_to_u32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for bfloat16 to uint64 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_u64_avx512bf16() — Requires: AVX512F, AVX512BF16,
 * AVX512VL, AVX512DQ
 * - Index 1: tbf16_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_u64[] = {tbf16_to_u64_avx512bf16,
                                      tbf16_to_u64_scalar};
#else
/**
 * @brief Dispatch table for bfloat16 to uint64 conversions.
 *
 * Variants:
 * - Index 0: tbf16_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_tbf16_to_u64[] = {tbf16_to_u64_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for double to uint8 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_u8_avx512() — Requires: AVX512F
 * - Index 1: tf64_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_u8[] = {tf64_to_u8_avx512, tf64_to_u8_scalar};
#else
/**
 * @brief Dispatch table for double to uint8 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_u8[] = {tf64_to_u8_scalar};
#endif

/**
 * @brief Dispatch table for double to uint16 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_u16_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_u16[] = {tf64_to_u16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for double to uint32 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_u32_avx512() — Requires: AVX512F
 * - Index 1: tf64_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_u32[] = {tf64_to_u32_avx512, tf64_to_u32_scalar};
#else
/**
 * @brief Dispatch table for double to uint32 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_u32[] = {tf64_to_u32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for double to uint64 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_u64_avx512() — Requires: AVX512F, AVX512DQ
 * - Index 1: tf64_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_u64[] = {tf64_to_u64_avx512, tf64_to_u64_scalar};
#else
/**
 * @brief Dispatch table for double to uint64 conversions.
 *
 * Variants:
 * - Index 0: tf64_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_tf64_to_u64[] = {tf64_to_u64_scalar};
#endif

/**
 * @brief Dispatch table for int8 to float4_e2m1fn_x2 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_fp4e2m1_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_fp4e2m1[] = {ts8_to_fp4e2m1_scalar};

/**
 * @brief Dispatch table for int8 to float8_e4m3fn conversions.
 *
 * Variants:
 * - Index 0: ts8_to_fp8e4m3_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_fp8e4m3[] = {ts8_to_fp8e4m3_scalar};

/**
 * @brief Dispatch table for int8 to float8_e5m2 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_fp8e5m2_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_fp8e5m2[] = {ts8_to_fp8e5m2_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int8 to float16 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_fp16_avx512() — Requires: AVX512F, AVX512FP16
 * - Index 1: ts8_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_fp16[] = {ts8_to_fp16_avx512, ts8_to_fp16_scalar};
#else
/**
 * @brief Dispatch table for int8 to float16 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_fp16[] = {ts8_to_fp16_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int8 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_bf16_avx512bf16() — Requires: AVX512F, AVX512BF16
 * - Index 1: ts8_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_bf16[] = {ts8_to_bf16_avx512bf16,
                                     ts8_to_bf16_scalar};
#else
/**
 * @brief Dispatch table for int8 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_bf16[] = {ts8_to_bf16_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int8 to float conversions.
 *
 * Variants:
 * - Index 0: ts8_to_f32_avx512() — Requires: AVX512F
 * - Index 1: ts8_to_f32_avx2() — Requires: AVX2
 * - Index 2: ts8_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_f32[] = {ts8_to_f32_avx512, ts8_to_f32_avx2,
                                    ts8_to_f32_scalar};
#else
/**
 * @brief Dispatch table for int8 to float conversions.
 *
 * Variants:
 * - Index 0: ts8_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_f32[] = {ts8_to_f32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int8 to double conversions.
 *
 * Variants:
 * - Index 0: ts8_to_f64_avx512() — Requires: AVX512F
 * - Index 1: ts8_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_f64[] = {ts8_to_f64_avx512, ts8_to_f64_scalar};
#else
/**
 * @brief Dispatch table for int8 to double conversions.
 *
 * Variants:
 * - Index 0: ts8_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_f64[] = {ts8_to_f64_scalar};
#endif

/**
 * @brief Dispatch table for int16 to float4_e2m1fn_x2 conversions.
 *
 * Variants:
 * - Index 0: ts16_to_fp4e2m1_scalar() — Portable fallback
 */
const CastFn lookup_ts16_to_fp4e2m1[] = {ts16_to_fp4e2m1_scalar};

/**
 * @brief Dispatch table for int16 to float8_e4m3fn conversions.
 *
 * Variants:
 * - Index 0: ts16_to_fp8e4m3_scalar() — Portable fallback
 */
const CastFn lookup_ts16_to_fp8e4m3[] = {ts16_to_fp8e4m3_scalar};

/**
 * @brief Dispatch table for int16 to float8_e5m2 conversions.
 *
 * Variants:
 * - Index 0: ts16_to_fp8e5m2_scalar() — Portable fallback
 */
const CastFn lookup_ts16_to_fp8e5m2[] = {ts16_to_fp8e5m2_scalar};

/**
 * @brief Dispatch table for int16 to float16 conversions.
 *
 * Variants:
 * - Index 0: ts16_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_ts16_to_fp16[] = {ts16_to_fp16_scalar};

/**
 * @brief Dispatch table for int16 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: ts16_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_ts16_to_bf16[] = {ts16_to_bf16_scalar};

/**
 * @brief Dispatch table for int16 to float conversions.
 *
 * Variants:
 * - Index 0: ts16_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_ts16_to_f32[] = {ts16_to_f32_scalar};

/**
 * @brief Dispatch table for int16 to double conversions.
 *
 * Variants:
 * - Index 0: ts16_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_ts16_to_f64[] = {ts16_to_f64_scalar};

/**
 * @brief Dispatch table for int32 to float4_e2m1fn_x2 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_fp4e2m1_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_fp4e2m1[] = {ts32_to_fp4e2m1_scalar};

/**
 * @brief Dispatch table for int32 to float8_e4m3fn conversions.
 *
 * Variants:
 * - Index 0: ts32_to_fp8e4m3_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_fp8e4m3[] = {ts32_to_fp8e4m3_scalar};

/**
 * @brief Dispatch table for int32 to float8_e5m2 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_fp8e5m2_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_fp8e5m2[] = {ts32_to_fp8e5m2_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int32 to float16 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_fp16_avx512fp16() — Requires: AVX512F, AVX512FP16
 * - Index 1: ts32_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_fp16[] = {ts32_to_fp16_avx512fp16,
                                      ts32_to_fp16_scalar};
#else
/**
 * @brief Dispatch table for int32 to float16 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_fp16[] = {ts32_to_fp16_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int32 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_bf16_avx512bf16() — Requires: AVX512F, AVX512BF16
 * - Index 1: ts32_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_bf16[] = {ts32_to_bf16_avx512bf16,
                                      ts32_to_bf16_scalar};
#else
/**
 * @brief Dispatch table for int32 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_bf16[] = {ts32_to_bf16_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int32 to float conversions.
 *
 * Variants:
 * - Index 0: ts32_to_f32_avx512() — Requires: AVX512F
 * - Index 1: ts32_to_f32_avx_avx2() — Requires: AVX/AVX2
 * - Index 2: ts32_to_f32_sse4_2() — Requires: SSE4.2
 * - Index 3: ts32_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_f32[] = {ts32_to_f32_avx512, ts32_to_f32_avx_avx2,
                                     ts32_to_f32_sse4_2, ts32_to_f32_scalar};
#else
/**
 * @brief Dispatch table for int32 to float conversions.
 *
 * Variants:
 * - Index 0: ts32_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_f32[] = {ts32_to_f32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int32 to double conversions.
 *
 * Variants:
 * - Index 0: ts32_to_f64_avx512() — Requires: AVX512F
 * - Index 1: ts32_to_f64_avx_avx2() — Requires: AVX/AVX2
 * - Index 2: ts32_to_f64_sse4_2() — Requires: SSE4.2
 * - Index 3: ts32_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_f64[] = {ts32_to_f64_avx512, ts32_to_f64_avx_avx2,
                                     ts32_to_f64_sse4_2, ts32_to_f64_scalar};
#else
/**
 * @brief Dispatch table for int32 to double conversions.
 *
 * Variants:
 * - Index 0: ts32_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_f64[] = {ts32_to_f64_scalar};
#endif

/**
 * @brief Dispatch table for int64 to float4_e2m1fn_x2 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_fp4e2m1_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_fp4e2m1[] = {ts64_to_fp4e2m1_scalar};

/**
 * @brief Dispatch table for int64 to float8_e4m3fn conversions.
 *
 * Variants:
 * - Index 0: ts64_to_fp8e4m3_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_fp8e4m3[] = {ts64_to_fp8e4m3_scalar};

/**
 * @brief Dispatch table for int64 to float8_e5m2 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_fp8e5m2_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_fp8e5m2[] = {ts64_to_fp8e5m2_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int64 to float16 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_fp16_avx512fp16() — Requires: AVX512F, AVX512FP16
 * - Index 1: ts64_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_fp16[] = {ts64_to_fp16_avx512fp16,
                                      ts64_to_fp16_scalar};
#else
/**
 * @brief Dispatch table for int64 to float16 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_fp16[] = {ts64_to_fp16_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int64 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_bf16_avx512bf16() — Requires: AVX512F, AVX512DQ,
 * AVX512BF16, AVX512VL
 * - Index 1: ts64_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_bf16[] = {ts64_to_bf16_avx512bf16,
                                      ts64_to_bf16_scalar};
#else
/**
 * @brief Dispatch table for int64 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_bf16[] = {ts64_to_bf16_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int64 to float conversions.
 *
 * Variants:
 * - Index 0: ts64_to_f32_avx512() — Requires: AVX512F, AVX512DQ
 * - Index 1: ts64_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_f32[] = {ts64_to_f32_avx512, ts64_to_f32_scalar};
#else
/**
 * @brief Dispatch table for int64 to float conversions.
 *
 * Variants:
 * - Index 0: ts64_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_f32[] = {ts64_to_f32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int64 to double conversions.
 *
 * Variants:
 * - Index 0: ts64_to_f64_avx512() — Requires: AVX512F, AVX512DQ
 * - Index 1: ts64_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_f64[] = {ts64_to_f64_avx512, ts64_to_f64_scalar};
#else
/**
 * @brief Dispatch table for int64 to double conversions.
 *
 * Variants:
 * - Index 0: ts64_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_f64[] = {ts64_to_f64_scalar};
#endif

/**
 * @brief Dispatch table for int8 to int16 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_s16_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_s16[] = {ts8_to_s16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int8 to int32 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_s32_avx512() — Requires: AVX512F
 * - Index 1: ts8_to_s32_avx2() — Requires: AVX2
 * - Index 2: ts8_to_s32_sse4_2() — Requires: SSE4.2
 * - Index 3: ts8_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_s32[] = {ts8_to_s32_avx512, ts8_to_s32_avx2,
                                    ts8_to_s32_sse4_2, ts8_to_s32_scalar};
#else
/**
 * @brief Dispatch table for int8 to int32 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_s32[] = {ts8_to_s32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int8 to int64 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_s64_avx512() — Requires: AVX512F
 * - Index 1: ts8_to_s64_avx2() — Requires: AVX2
 * - Index 2: ts8_to_s64_sse4_2() — Requires: SSE4.2
 * - Index 3: ts8_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_s64[] = {ts8_to_s64_avx512, ts8_to_s64_avx2,
                                    ts8_to_s64_sse4_2, ts8_to_s64_scalar};
#else
/**
 * @brief Dispatch table for int8 to int64 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_s64[] = {ts8_to_s64_scalar};
#endif

/**
 * @brief Dispatch table for int16 to int8 conversions.
 *
 * Variants:
 * - Index 0: ts16_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_ts16_to_s8[] = {ts16_to_s8_scalar};

/**
 * @brief Dispatch table for int16 to int32 conversions.
 *
 * Variants:
 * - Index 0: ts16_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_ts16_to_s32[] = {ts16_to_s32_scalar};

/**
 * @brief Dispatch table for int16 to int64 conversions.
 *
 * Variants:
 * - Index 0: ts16_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_ts16_to_s64[] = {ts16_to_s64_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int32 to int8 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_s8_avx512() — Requires: AVX512F
 * - Index 1: ts32_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_s8[] = {ts32_to_s8_avx512, ts32_to_s8_scalar};
#else
/**
 * @brief Dispatch table for int32 to int8 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_s8[] = {ts32_to_s8_scalar};
#endif

/**
 * @brief Dispatch table for int32 to int16 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_s16_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_s16[] = {ts32_to_s16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int32 to int64 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_s64_avx512() — Requires: AVX512F
 * - Index 1: ts32_to_s64_avx2() — Requires: AVX2
 * - Index 2: ts32_to_s64_sse4_2() — Requires: SSE4.2
 * - Index 3: ts32_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_s64[] = {ts32_to_s64_avx512, ts32_to_s64_avx2,
                                     ts32_to_s64_sse4_2, ts32_to_s64_scalar};
#else
/**
 * @brief Dispatch table for int32 to int64 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_s64[] = {ts32_to_s64_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int64 to int8 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_s8_avx512() — Requires: AVX512F, AVX512BW
 * - Index 1: ts64_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_s8[] = {ts64_to_s8_avx512, ts64_to_s8_scalar};
#else
/**
 * @brief Dispatch table for int64 to int8 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_s8[] = {ts64_to_s8_scalar};
#endif

/**
 * @brief Dispatch table for int64 to int16 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_s16_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_s16[] = {ts64_to_s16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int64 to int32 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_s32_avx512() — Requires: AVX512F
 * - Index 1: ts64_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_s32[] = {ts64_to_s32_avx512, ts64_to_s32_scalar};
#else
/**
 * @brief Dispatch table for int64 to int32 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_s32[] = {ts64_to_s32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int8 to uint8 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_u8_avx512() — Requires: AVX512F
 * - Index 1: ts8_to_u8_avx_avx2() — Requires: AVX/AVX2
 * - Index 2: ts8_to_u8_sse4_2() — Requires: SSE4.2
 * - Index 3: ts8_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_u8[] = {ts8_to_u8_avx512, ts8_to_u8_avx_avx2,
                                   ts8_to_u8_sse4_2, ts8_to_u8_scalar};
#else
/**
 * @brief Dispatch table for int8 to uint8 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_u8[] = {ts8_to_u8_scalar};
#endif

/**
 * @brief Dispatch table for int8 to uint16 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_u16_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_u16[] = {ts8_to_u16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int8 to uint32 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_u32_avx512() — Requires: AVX512F
 * - Index 1: ts8_to_u32_avx2() — Requires: AVX2
 * - Index 2: ts8_to_u32_sse4_2() — Requires: SSE4.2
 * - Index 3: ts8_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_u32[] = {ts8_to_u32_avx512, ts8_to_u32_avx2,
                                    ts8_to_u32_sse4_2, ts8_to_u32_scalar};
#else
/**
 * @brief Dispatch table for int8 to uint32 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_u32[] = {ts8_to_u32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int8 to uint64 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_u64_avx512() — Requires: AVX512F
 * - Index 1: ts8_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_u64[] = {ts8_to_u64_avx512, ts8_to_u64_scalar};
#else
/**
 * @brief Dispatch table for int8 to uint64 conversions.
 *
 * Variants:
 * - Index 0: ts8_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_ts8_to_u64[] = {ts8_to_u64_scalar};
#endif

/**
 * @brief Dispatch table for int16 to uint8 conversions.
 *
 * Variants:
 * - Index 0: ts16_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_ts16_to_u8[] = {ts16_to_u8_scalar};

/**
 * @brief Dispatch table for int16 to uint16 conversions.
 *
 * Variants:
 * - Index 0: ts16_to_u16_scalar() — Portable fallback
 */
const CastFn lookup_ts16_to_u16[] = {ts16_to_u16_scalar};

/**
 * @brief Dispatch table for int16 to uint32 conversions.
 *
 * Variants:
 * - Index 0: ts16_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_ts16_to_u32[] = {ts16_to_u32_scalar};

/**
 * @brief Dispatch table for int16 to uint64 conversions.
 *
 * Variants:
 * - Index 0: ts16_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_ts16_to_u64[] = {ts16_to_u64_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int32 to uint8 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_u8_avx512() — Requires: AVX512F, AVX512BW
 * - Index 1: ts32_to_u8_avx2() — Requires: AVX2
 * - Index 2: ts32_to_u8_sse4_2() — Requires: SSE4.2
 * - Index 3: ts32_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_u8[] = {ts32_to_u8_avx512, ts32_to_u8_avx2,
                                    ts32_to_u8_sse4_2, ts32_to_u8_scalar};
#else
/**
 * @brief Dispatch table for int32 to uint8 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_u8[] = {ts32_to_u8_scalar};
#endif

/**
 * @brief Dispatch table for int32 to uint16 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_u16_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_u16[] = {ts32_to_u16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int32 to uint32 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_u32_avx512() — Requires: AVX512F
 * - Index 1: ts32_to_u32_avx_avx2() — Requires: AVX/AVX2
 * - Index 2: ts32_to_u32_sse4_2() — Requires: SSE4.2
 * - Index 3: ts32_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_u32[] = {ts32_to_u32_avx512, ts32_to_u32_avx_avx2,
                                     ts32_to_u32_sse4_2, ts32_to_u32_scalar};
#else
/**
 * @brief Dispatch table for int32 to uint32 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_u32[] = {ts32_to_u32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int32 to uint64 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_u64_avx512() — Requires: AVX512F
 * - Index 1: ts32_to_u64_avx2() — Requires: AVX2
 * - Index 2: ts32_to_u64_sse4_2() — Requires: SSE4.2
 * - Index 3: ts32_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_u64[] = {ts32_to_u64_avx512, ts32_to_u64_avx2,
                                     ts32_to_u64_sse4_2, ts32_to_u64_scalar};
#else
/**
 * @brief Dispatch table for int32 to uint64 conversions.
 *
 * Variants:
 * - Index 0: ts32_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_ts32_to_u64[] = {ts32_to_u64_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int64 to uint8 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_u8_avx512() — Requires: AVX512F
 * - Index 1: ts64_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_u8[] = {ts64_to_u8_avx512, ts64_to_u8_scalar};
#else
/**
 * @brief Dispatch table for int64 to uint8 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_u8[] = {ts64_to_u8_scalar};
#endif

/**
 * @brief Dispatch table for int64 to uint16 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_u16_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_u16[] = {ts64_to_u16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int64 to uint32 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_u32_avx512() — Requires: AVX512F
 * - Index 1: ts64_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_u32[] = {ts64_to_u32_avx512, ts64_to_u32_scalar};
#else
/**
 * @brief Dispatch table for int64 to uint32 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_u32[] = {ts64_to_u32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for int64 to uint64 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_u64_avx512() — Requires: AVX512F
 * - Index 1: ts64_to_u64_avx_avx2() — Requires: AVX/AVX2
 * - Index 2: ts64_to_u64_sse4_2() — Requires: SSE4.2
 * - Index 3: ts64_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_u64[] = {ts64_to_u64_avx512, ts64_to_u64_avx_avx2,
                                     ts64_to_u64_sse4_2, ts64_to_u64_scalar};
#else
/**
 * @brief Dispatch table for int64 to uint64 conversions.
 *
 * Variants:
 * - Index 0: ts64_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_ts64_to_u64[] = {ts64_to_u64_scalar};
#endif

/**
 * @brief Dispatch table for uint8 to float4_e2m1fn_x2 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_fp4e2m1_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_fp4e2m1[] = {tu8_to_fp4e2m1_scalar};

/**
 * @brief Dispatch table for uint8 to float8_e4m3fn conversions.
 *
 * Variants:
 * - Index 0: tu8_to_fp8e4m3_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_fp8e4m3[] = {tu8_to_fp8e4m3_scalar};

/**
 * @brief Dispatch table for uint8 to float8_e5m2 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_fp8e5m2_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_fp8e5m2[] = {tu8_to_fp8e5m2_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint8 to float16 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_fp16_avx512fp16() — Requires: AVX512F, AVX512FP16
 * - Index 1: tu8_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_fp16[] = {tu8_to_fp16_avx512fp16,
                                     tu8_to_fp16_scalar};
#else
/**
 * @brief Dispatch table for uint8 to float16 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_fp16[] = {tu8_to_fp16_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint8 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_bf16_avx512bf16() — Requires: AVX512F, AVX512BF16
 * - Index 1: tu8_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_bf16[] = {tu8_to_bf16_avx512bf16,
                                     tu8_to_bf16_scalar};
#else
/**
 * @brief Dispatch table for uint8 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_bf16[] = {tu8_to_bf16_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint8 to float conversions.
 *
 * Variants:
 * - Index 0: tu8_to_f32_avx512() — Requires: AVX512F
 * - Index 1: tu8_to_f32_avx2() — Requires: AVX2
 * - Index 2: tu8_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_f32[] = {tu8_to_f32_avx512, tu8_to_f32_avx2,
                                    tu8_to_f32_scalar};
#else
/**
 * @brief Dispatch table for uint8 to float conversions.
 *
 * Variants:
 * - Index 0: tu8_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_f32[] = {tu8_to_f32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint8 to double conversions.
 *
 * Variants:
 * - Index 0: tu8_to_f64_avx512() — Requires: AVX512F
 * - Index 1: tu8_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_f64[] = {tu8_to_f64_avx512, tu8_to_f64_scalar};
#else
/**
 * @brief Dispatch table for uint8 to double conversions.
 *
 * Variants:
 * - Index 0: tu8_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_f64[] = {tu8_to_f64_scalar};
#endif

/**
 * @brief Dispatch table for uint16 to float4_e2m1fn_x2 conversions.
 *
 * Variants:
 * - Index 0: tu16_to_fp4e2m1_scalar() — Portable fallback
 */
const CastFn lookup_tu16_to_fp4e2m1[] = {tu16_to_fp4e2m1_scalar};

/**
 * @brief Dispatch table for uint16 to float8_e4m3fn conversions.
 *
 * Variants:
 * - Index 0: tu16_to_fp8e4m3_scalar() — Portable fallback
 */
const CastFn lookup_tu16_to_fp8e4m3[] = {tu16_to_fp8e4m3_scalar};

/**
 * @brief Dispatch table for uint16 to float8_e5m2 conversions.
 *
 * Variants:
 * - Index 0: tu16_to_fp8e5m2_scalar() — Portable fallback
 */
const CastFn lookup_tu16_to_fp8e5m2[] = {tu16_to_fp8e5m2_scalar};

/**
 * @brief Dispatch table for uint16 to float16 conversions.
 *
 * Variants:
 * - Index 0: tu16_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_tu16_to_fp16[] = {tu16_to_fp16_scalar};

/**
 * @brief Dispatch table for uint16 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: tu16_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_tu16_to_bf16[] = {tu16_to_bf16_scalar};

/**
 * @brief Dispatch table for uint16 to float conversions.
 *
 * Variants:
 * - Index 0: tu16_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_tu16_to_f32[] = {tu16_to_f32_scalar};

/**
 * @brief Dispatch table for uint16 to double conversions.
 *
 * Variants:
 * - Index 0: tu16_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_tu16_to_f64[] = {tu16_to_f64_scalar};

/**
 * @brief Dispatch table for uint32 to float4_e2m1fn_x2 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_fp4e2m1_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_fp4e2m1[] = {tu32_to_fp4e2m1_scalar};

/**
 * @brief Dispatch table for uint32 to float8_e4m3fn conversions.
 *
 * Variants:
 * - Index 0: tu32_to_fp8e4m3_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_fp8e4m3[] = {tu32_to_fp8e4m3_scalar};

/**
 * @brief Dispatch table for uint32 to float8_e5m2 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_fp8e5m2_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_fp8e5m2[] = {tu32_to_fp8e5m2_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint32 to float16 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_fp16_avx512fp16() — Requires: AVX512F, AVX512FP16
 * - Index 1: tu32_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_fp16[] = {tu32_to_fp16_avx512fp16,
                                      tu32_to_fp16_scalar};
#else
/**
 * @brief Dispatch table for uint32 to float16 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_fp16[] = {tu32_to_fp16_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint32 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_bf16_avx512bf16() — Requires: AVX512F, AVX512BF16
 * - Index 1: tu32_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_bf16[] = {tu32_to_bf16_avx512bf16,
                                      tu32_to_bf16_scalar};
#else
/**
 * @brief Dispatch table for uint32 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_bf16[] = {tu32_to_bf16_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint32 to float conversions.
 *
 * Variants:
 * - Index 0: tu32_to_f32_avx512() — Requires: AVX512F
 * - Index 1: tu32_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_f32[] = {tu32_to_f32_avx512, tu32_to_f32_scalar};
#else
/**
 * @brief Dispatch table for uint32 to float conversions.
 *
 * Variants:
 * - Index 0: tu32_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_f32[] = {tu32_to_f32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint32 to double conversions.
 *
 * Variants:
 * - Index 0: tu32_to_f64_avx512() — Requires: AVX512F
 * - Index 1: tu32_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_f64[] = {tu32_to_f64_avx512, tu32_to_f64_scalar};
#else
/**
 * @brief Dispatch table for uint32 to double conversions.
 *
 * Variants:
 * - Index 0: tu32_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_f64[] = {tu32_to_f64_scalar};
#endif

/**
 * @brief Dispatch table for uint64 to float4_e2m1fn_x2 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_fp4e2m1_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_fp4e2m1[] = {tu64_to_fp4e2m1_scalar};

/**
 * @brief Dispatch table for uint64 to float8_e4m3fn conversions.
 *
 * Variants:
 * - Index 0: tu64_to_fp8e4m3_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_fp8e4m3[] = {tu64_to_fp8e4m3_scalar};

/**
 * @brief Dispatch table for uint64 to float8_e5m2 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_fp8e5m2_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_fp8e5m2[] = {tu64_to_fp8e5m2_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint64 to float16 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_fp16_avx512fp16() — Requires: AVX512F, AVX512FP16
 * - Index 1: tu64_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_fp16[] = {tu64_to_fp16_avx512fp16,
                                      tu64_to_fp16_scalar};
#else
/**
 * @brief Dispatch table for uint64 to float16 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_fp16_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_fp16[] = {tu64_to_fp16_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint64 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_bf16_avx512bf16() — Requires: AVX512F, AVX512DQ,
 * AVX512BF16, AVX512VL
 * - Index 1: tu64_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_bf16[] = {tu64_to_bf16_avx512bf16,
                                      tu64_to_bf16_scalar};
#else
/**
 * @brief Dispatch table for uint64 to bfloat16 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_bf16_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_bf16[] = {tu64_to_bf16_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint64 to float conversions.
 *
 * Variants:
 * - Index 0: tu64_to_f32_avx512() — Requires: AVX512F, AVX512DQ
 * - Index 1: tu64_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_f32[] = {tu64_to_f32_avx512, tu64_to_f32_scalar};
#else
/**
 * @brief Dispatch table for uint64 to float conversions.
 *
 * Variants:
 * - Index 0: tu64_to_f32_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_f32[] = {tu64_to_f32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint64 to double conversions.
 *
 * Variants:
 * - Index 0: tu64_to_f64_avx512() — Requires: AVX512F, AVX512DQ
 * - Index 1: tu64_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_f64[] = {tu64_to_f64_avx512, tu64_to_f64_scalar};
#else
/**
 * @brief Dispatch table for uint64 to double conversions.
 *
 * Variants:
 * - Index 0: tu64_to_f64_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_f64[] = {tu64_to_f64_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint8 to int8 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_s8_avx512() — Requires: AVX512F, AVX512BW
 * - Index 1: tu8_to_s8_avx2() — Requires: AVX2
 * - Index 2: tu8_to_s8_sse4_2() — Requires: SSE4.2
 * - Index 3: tu8_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_s8[] = {tu8_to_s8_avx512, tu8_to_s8_avx2,
                                   tu8_to_s8_sse4_2, tu8_to_s8_scalar};
#else
/**
 * @brief Dispatch table for uint8 to int8 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_s8[] = {tu8_to_s8_scalar};
#endif

/**
 * @brief Dispatch table for uint8 to int16 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_s16_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_s16[] = {tu8_to_s16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint8 to int32 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_s32_avx512() — Requires: AVX512F
 * - Index 1: tu8_to_s32_avx2() — Requires: AVX2
 * - Index 2: tu8_to_s32_sse4_2() — Requires: SSE4.2
 * - Index 3: tu8_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_s32[] = {tu8_to_s32_avx512, tu8_to_s32_avx2,
                                    tu8_to_s32_sse4_2, tu8_to_s32_scalar};
#else
/**
 * @brief Dispatch table for uint8 to int32 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_s32[] = {tu8_to_s32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint8 to int64 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_s64_avx512() — Requires: AVX512F
 * - Index 1: tu8_to_s64_avx2() — Requires: AVX2
 * - Index 2: tu8_to_s64_sse4_2() — Requires: SSE4.2
 * - Index 3: tu8_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_s64[] = {tu8_to_s64_avx512, tu8_to_s64_avx2,
                                    tu8_to_s64_sse4_2, tu8_to_s64_scalar};
#else
/**
 * @brief Dispatch table for uint8 to int64 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_s64[] = {tu8_to_s64_scalar};
#endif

/**
 * @brief Dispatch table for uint16 to int8 conversions.
 *
 * Variants:
 * - Index 0: tu16_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tu16_to_s8[] = {tu16_to_s8_scalar};

/**
 * @brief Dispatch table for uint16 to int16 conversions.
 *
 * Variants:
 * - Index 0: tu16_to_s16_scalar() — Portable fallback
 */
const CastFn lookup_tu16_to_s16[] = {tu16_to_s16_scalar};

/**
 * @brief Dispatch table for uint16 to int32 conversions.
 *
 * Variants:
 * - Index 0: tu16_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tu16_to_s32[] = {tu16_to_s32_scalar};

/**
 * @brief Dispatch table for uint16 to int64 conversions.
 *
 * Variants:
 * - Index 0: tu16_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tu16_to_s64[] = {tu16_to_s64_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint32 to int8 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_s8_avx512() — Requires: AVX512F, AVX512BW
 * - Index 1: tu32_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_s8[] = {tu32_to_s8_avx512, tu32_to_s8_scalar};
#else
/**
 * @brief Dispatch table for uint32 to int8 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_s8[] = {tu32_to_s8_scalar};
#endif

/**
 * @brief Dispatch table for uint32 to int16 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_s16_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_s16[] = {tu32_to_s16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint32 to int32 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_s32_avx512() — Requires: AVX512F
 * - Index 1: tu32_to_s32_avx_avx2() — Requires: AVX/AVX2
 * - Index 2: tu32_to_s32_sse4_2() — Requires: SSE4.2
 * - Index 3: tu32_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_s32[] = {tu32_to_s32_avx512, tu32_to_s32_avx_avx2,
                                     tu32_to_s32_sse4_2, tu32_to_s32_scalar};
#else
/**
 * @brief Dispatch table for uint32 to int32 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_s32[] = {tu32_to_s32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint32 to int64 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_s64_avx512() — Requires: AVX512F
 * - Index 1: tu32_to_s64_avx2() — Requires: AVX2
 * - Index 2: tu32_to_s64_sse4_2() — Requires: SSE4.2
 * - Index 3: tu32_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_s64[] = {tu32_to_s64_avx512, tu32_to_s64_avx2,
                                     tu32_to_s64_sse4_2, tu32_to_s64_scalar};
#else
/**
 * @brief Dispatch table for uint32 to int64 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_s64[] = {tu32_to_s64_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint64 to int8 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_s8_avx512() — Requires: AVX512F
 * - Index 1: tu64_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_s8[] = {tu64_to_s8_avx512, tu64_to_s8_scalar};
#else
/**
 * @brief Dispatch table for uint64 to int8 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_s8_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_s8[] = {tu64_to_s8_scalar};
#endif

/**
 * @brief Dispatch table for uint64 to int16 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_s16_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_s16[] = {tu64_to_s16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint64 to int32 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_s32_avx512() — Requires: AVX512F
 * - Index 1: tu64_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_s32[] = {tu64_to_s32_avx512, tu64_to_s32_scalar};
#else
/**
 * @brief Dispatch table for uint64 to int32 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_s32_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_s32[] = {tu64_to_s32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint64 to int64 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_s64_avx512() — Requires: AVX512F
 * - Index 1: tu64_to_s64_avx_avx2() — Requires: AVX/AVX2
 * - Index 2: tu64_to_s64_sse4_2() — Requires: SSE4.2
 * - Index 3: tu64_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_s64[] = {tu64_to_s64_avx512, tu64_to_s64_avx_avx2,
                                     tu64_to_s64_sse4_2, tu64_to_s64_scalar};
#else
/**
 * @brief Dispatch table for uint64 to int64 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_s64_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_s64[] = {tu64_to_s64_scalar};
#endif

/**
 * @brief Dispatch table for uint8 to uint16 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_u16_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_u16[] = {tu8_to_u16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint8 to uint32 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_u32_avx512() — Requires: AVX512F
 * - Index 1: tu8_to_u32_avx2() — Requires: AVX2
 * - Index 2: tu8_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_u32[] = {tu8_to_u32_avx512, tu8_to_u32_avx2,
                                    tu8_to_u32_scalar};
#else
/**
 * @brief Dispatch table for uint8 to uint32 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_u32[] = {tu8_to_u32_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint8 to uint64 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_u64_avx512() — Requires: AVX512F
 * - Index 1: tu8_to_u64_avx2() — Requires: AVX2
 * - Index 2: tu8_to_u64_sse4_2() — Requires: SSE4.2
 * - Index 3: tu8_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_u64[] = {tu8_to_u64_avx512, tu8_to_u64_avx2,
                                    tu8_to_u64_sse4_2, tu8_to_u64_scalar};
#else
/**
 * @brief Dispatch table for uint8 to uint64 conversions.
 *
 * Variants:
 * - Index 0: tu8_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_tu8_to_u64[] = {tu8_to_u64_scalar};
#endif

/**
 * @brief Dispatch table for uint16 to uint8 conversions.
 *
 * Variants:
 * - Index 0: tu16_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_tu16_to_u8[] = {tu16_to_u8_scalar};

/**
 * @brief Dispatch table for uint16 to uint32 conversions.
 *
 * Variants:
 * - Index 0: tu16_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_tu16_to_u32[] = {tu16_to_u32_scalar};

/**
 * @brief Dispatch table for uint16 to uint64 conversions.
 *
 * Variants:
 * - Index 0: tu16_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_tu16_to_u64[] = {tu16_to_u64_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint32 to uint8 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_u8_avx512() — Requires: AVX512F
 * - Index 1: tu32_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_u8[] = {tu32_to_u8_avx512, tu32_to_u8_scalar};
#else
/**
 * @brief Dispatch table for uint32 to uint8 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_u8[] = {tu32_to_u8_scalar};
#endif

/**
 * @brief Dispatch table for uint32 to uint16 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_u16_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_u16[] = {tu32_to_u16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint32 to uint64 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_u64_avx512() — Requires: AVX512F
 * - Index 1: tu32_to_u64_avx2() — Requires: AVX2
 * - Index 2: tu32_to_u64_sse4_2() — Requires: SSE4.2
 * - Index 3: tu32_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_u64[] = {tu32_to_u64_avx512, tu32_to_u64_avx2,
                                     tu32_to_u64_sse4_2, tu32_to_u64_scalar};
#else
/**
 * @brief Dispatch table for uint32 to uint64 conversions.
 *
 * Variants:
 * - Index 0: tu32_to_u64_scalar() — Portable fallback
 */
const CastFn lookup_tu32_to_u64[] = {tu32_to_u64_scalar};
#endif

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint64 to uint8 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_u8_avx512() — Requires: AVX512F, AVX512BW
 * - Index 1: tu64_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_u8[] = {tu64_to_u8_avx512, tu64_to_u8_scalar};
#else
/**
 * @brief Dispatch table for uint64 to uint8 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_u8_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_u8[] = {tu64_to_u8_scalar};
#endif

/**
 * @brief Dispatch table for uint64 to uint16 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_u16_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_u16[] = {tu64_to_u16_scalar};

#ifdef _GNUC_CLANG_
/**
 * @brief Dispatch table for uint64 to uint32 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_u32_avx512() — Requires: AVX512F
 * - Index 1: tu64_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_u32[] = {tu64_to_u32_avx512, tu64_to_u32_scalar};
#else
/**
 * @brief Dispatch table for uint64 to uint32 conversions.
 *
 * Variants:
 * - Index 0: tu64_to_u32_scalar() — Portable fallback
 */
const CastFn lookup_tu64_to_u32[] = {tu64_to_u32_scalar};
#endif
