/**
 * @file Dispatch_test.cpp
 * @brief Tests for the load-time cast dispatch machinery.
 *
 * Verifies that the NUM_DTYPES x NUM_DTYPES cast_dispatch matrix resolves a
 * kernel for exactly the 210 pairs generated by the cast.h X-macro families,
 * stays null on the diagonal and for every quantized pair, agrees with the
 * per-pair dispatch wrappers behaviorally, and that dtype_size /
 * dtype_packing_factor report their documented values.
 *
 * Per ncore's trust boundary, unsupported pairs are exercised only through
 * get_dispatched_cast_func(); cast() itself is never invoked with a pair
 * whose resolved pointer is null.
 */

#include <gtest/gtest.h>

#include <array>
#include <cstdint>
#include <cstring>
#include <vector>

#include <ncore/core/device.h>
#include <ncore/core/dtype.h>
#include <ncore/core/status.h>
#include <ncore/headeronly/cast.h>
#include <ncore/headeronly/macros.h>
#include <ncore/headeronly/wrappers/tensor.hh>
#include <ncore/tensor.h>

#include "utils/Oracle.hpp"

namespace {

using tests::casting::allPairs;
using tests::casting::findPairFor;
using tests::casting::makePair;
using tests::casting::payloadEqual;
using tests::casting::readRaw;
using tests::casting::writeRaw;

/// The six quantized dtypes (no cast kernels are registered for them).
constexpr std::array<DType_, 6> kQuantizedDtypes{{
    DType_::QSigned8,
    DType_::QUnSigned8,
    DType_::QSigned16,
    DType_::QUnSigned16,
    DType_::QSigned32,
    DType_::QUnSigned32,
}};

/// One family-representative conversion with absolute expectations.
struct FamilySample {
  DType_ src;
  DType_ dst;
  uint64_t srcPattern; ///< Raw bits written into element 0.
  uint64_t dstPattern; ///< Expected raw bits in destination element 0.
  const char *label;
};

/// One representative per X-macro family; every value is exact in all
/// involved formats.
constexpr std::array<FamilySample, 7> kFamilySamples{{
    // Float -> Float: fp16 1.0 -> f32 1.0.
    {.src = DType_::Float16,
     .dst = DType_::Float32,
     .srcPattern = 0x3C00,
     .dstPattern = 0x3F800000,
     .label = "fp->fp"},
    // Float -> Int: f32 3.5 truncates to s8 3.
    {.src = DType_::Float32,
     .dst = DType_::Signed8,
     .srcPattern = 0x40600000,
     .dstPattern = 0x03,
     .label = "fp->int"},
    // Int -> Float: s8 -3 -> f32 -3.0.
    {.src = DType_::Signed8,
     .dst = DType_::Float32,
     .srcPattern = 0xFD,
     .dstPattern = 0xC0400000,
     .label = "int->fp"},
    // Signed -> Signed: s8 -5 -> s32 -5 (32-bit two's complement).
    {.src = DType_::Signed8,
     .dst = DType_::Signed32,
     .srcPattern = 0xFB,
     .dstPattern = 0xFFFFFFFBULL,
     .label = "s->s"},
    // Unsigned -> Unsigned: u8 200 -> u32 200.
    {.src = DType_::UnSigned8,
     .dst = DType_::UnSigned32,
     .srcPattern = 0xC8,
     .dstPattern = 0xC8,
     .label = "u->u"},
    // Signed -> Unsigned: s16 -1 -> u8 0 (ts16_to_u8 clamps negatives).
    {.src = DType_::Signed16,
     .dst = DType_::UnSigned8,
     .srcPattern = 0xFFFF,
     .dstPattern = 0x00,
     .label = "s->u"},
    // Unsigned -> Signed: u64 100 -> s8 100.
    {.src = DType_::UnSigned64,
     .dst = DType_::Signed8,
     .srcPattern = 100,
     .dstPattern = 100,
     .label = "u->s"},
}};

} // namespace

/**
 * @brief Verifies every X-macro-generated pair resolves to a non-null
 *        kernel and that the registry holds exactly 210 entries.
 */
TEST(Dispatch, AllSupportedPairsResolveToNonNull) {
  const auto &pairs = allPairs();
  ASSERT_EQ(pairs.size(), size_t{210});

  for (const auto &p : pairs) {
    EXPECT_NE(get_dispatched_cast_func(p.src, p.dst), nullptr) << p.label;
  }
}

/**
 * @brief Verifies diagonal entries are null: identity casts need no kernel.
 */
TEST(Dispatch, DiagonalPairsAreNull) {
  for (size_t i = 0; i < NUM_DTYPES; ++i) {
    const auto d = static_cast<DType_>(i);
    EXPECT_EQ(get_dispatched_cast_func(d, d), nullptr) << "dtype index=" << i;
  }
}

/**
 * @brief Verifies quantized rows and columns stay null: no quantized cast
 *        kernels exist yet (documented in cast.h).
 */
TEST(Dispatch, QuantizedPairsAreNull) {
  for (const DType_ q : kQuantizedDtypes) {
    for (size_t i = 0; i < NUM_DTYPES; ++i) {
      const auto d = static_cast<DType_>(i);
      EXPECT_EQ(get_dispatched_cast_func(q, d), nullptr)
          << "row q=" << static_cast<int>(q) << " d=" << i;
      EXPECT_EQ(get_dispatched_cast_func(d, q), nullptr)
          << "col d=" << i << " q=" << static_cast<int>(q);
    }
  }
}

/**
 * @brief Verifies behavioral agreement between the dispatch wrapper from
 *        cast.h and the kernel returned by get_dispatched_cast_func().
 */
TEST(Dispatch, ResolvedPointerMatchesDispatchWrapper) {
  for (const auto &sample : kFamilySamples) {
    SCOPED_TRACE(sample.label);
    const tests::casting::PairInfo *pair = findPairFor(sample.src, sample.dst);
    ASSERT_NE(pair, nullptr) << sample.label;

    CastFn resolved = get_dispatched_cast_func(sample.src, sample.dst);
    ASSERT_NE(resolved, nullptr);

    auto viaWrapper = makePair(sample.src, sample.dst, 4, 1U);
    auto viaResolved = makePair(sample.src, sample.dst, 4, 1U);
    ASSERT_TRUE(viaWrapper.ok);
    ASSERT_TRUE(viaResolved.ok);

    pair->wrapper(&viaWrapper.src.mutableCTensor(),
                  &viaWrapper.dst.mutableCTensor());
    resolved(&viaResolved.src.mutableCTensor(),
             &viaResolved.dst.mutableCTensor());

    size_t mismatch = 0;
    EXPECT_TRUE(payloadEqual(viaWrapper.dst.getCTensor(),
                             viaResolved.dst.getCTensor(), 4, &mismatch))
        << sample.label << " first mismatch at " << mismatch;
  }
}

/**
 * @brief Verifies one absolute-value conversion per X-macro family through
 *        the public cast() entry point.
 */
TEST(Dispatch, CastWritesExpectedValuesPerFamily) {
  for (const auto &sample : kFamilySamples) {
    SCOPED_TRACE(sample.label);
    auto pair = makePair(sample.src, sample.dst, 4, 1U);
    ASSERT_TRUE(pair.ok);

    writeRaw(pair.src.mutableCTensor(), 0, sample.srcPattern);
    cast(&pair.src.mutableCTensor(), &pair.dst.mutableCTensor(), sample.dst);

    EXPECT_EQ(readRaw(pair.dst.getCTensor(), 0), sample.dstPattern)
        << sample.label;
  }
}

/**
 * @brief Verifies metadata preservation and packed logical-size semantics
 *        through cast(): plain f32->f16 and packed f32->FP4.
 */
TEST(Dispatch, CastPreservesMetadataAndLogicalSize) {
  {
    SCOPED_TRACE("f32->f16");
    auto pair = makePair(DType_::Float32, DType_::Float16, 8, 1U);
    ASSERT_TRUE(pair.ok);

    cast(&pair.src.mutableCTensor(), &pair.dst.mutableCTensor(),
         DType_::Float16);

    const Tensor view = pair.dst.getCTensor();
    EXPECT_TRUE(is_allocated(&view));
    EXPECT_EQ(view.dtype, DType_::Float16);
    EXPECT_EQ(view.device, DEVICE_CPU);
    EXPECT_EQ(view.ndims, size_t{1});
    EXPECT_EQ(view.shape[0], size_t{8});
    EXPECT_EQ(view.size, size_t{8});
    EXPECT_EQ(view.logical_size, size_t{8});
  }
  {
    SCOPED_TRACE("f32->fp4");
    auto pair = makePair(DType_::Float32, DType_::Float4E2M1fn, 8, 1U);
    ASSERT_TRUE(pair.ok);
    ASSERT_EQ(pair.dst.getSize(), size_t{4}); // Packed storage units.

    cast(&pair.src.mutableCTensor(), &pair.dst.mutableCTensor(),
         DType_::Float4E2M1fn);

    const Tensor view = pair.dst.getCTensor();
    EXPECT_TRUE(is_allocated(&view));
    EXPECT_EQ(view.dtype, DType_::Float4E2M1fn);
    EXPECT_EQ(view.size, size_t{4});
    EXPECT_EQ(view.logical_size, size_t{8}); // 2 logical elements per byte.
  }
}

/**
 * @brief Verifies dtype_size against independent literal byte widths.
 */
TEST(Dispatch, DtypeSizeMatchesStorageTypeSizeof) {
  constexpr std::array<size_t, NUM_DTYPES> kSizes{{
      4, 8,       // Float32, Float64
      2, 2,       // Float16, BFloat16
      1, 1, 1,    // FP8 E4M3FN, FP8 E5M2, FP4 E2M1FNx2
      1, 1, 1, 1, // Signed8, UnSigned8, QSigned8, QUnSigned8
      2, 2, 2, 2, // Signed16, UnSigned16, QSigned16, QUnSigned16
      4, 4, 4, 4, // Signed32, UnSigned32, QSigned32, QUnSigned32
      8, 8,       // Signed64, UnSigned64
  }};
  for (size_t i = 0; i < NUM_DTYPES; ++i) {
    EXPECT_EQ(dtype_size(static_cast<DType_>(i)), kSizes[i])
        << "dtype index=" << i;
  }
}

/**
 * @brief Verifies the packing factor is 2 exclusively for Float4E2M1fn.
 */
TEST(Dispatch, PackingFactorIsTwoOnlyForFloat4) {
  for (size_t i = 0; i < NUM_DTYPES; ++i) {
    const auto d = static_cast<DType_>(i);
    EXPECT_EQ(dtype_packing_factor(d),
              d == DType_::Float4E2M1fn ? size_t{2} : size_t{1})
        << "dtype index=" << i;
  }
}
